### ISSUE TITLE
SPIKE: Research versioning for new electronic filing specifications

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#1104]
*   What does web upload expect for amendments filed to reports with older spec versions? What about backwards incompatibility? 
      *   The hypothetical I presented was a new report was filed using v8.2 and the amendment will be filed today (v8.4). 
            *   The amendment must be in v8.4
        *   Reports filed using out-of-date specs are rejected.
        *   FECFile software builds .fec file as per the current format specifications. All fields from previous versions will be mapped to latest version.

*   How long do vendors have to implement new specs? 
      *   Generally EFO gives vendors a two week comment period and an 90 day implementation period. 
            *   EFO provides the layouts and a list of changes including an explanation of the changes (RAD) two weeks prior to the start of the 90-day implementation period allowing vendors to review the changes and provide feedback.
        *   Once the format specs are finalized and published, we give the vendors 90 days to implement the changes.

In addition, once EFO updates the eFiling specifications in production, any **.fec file that is submitted (either original or amendment), *_must_** follow the new specifications or it will be rejected.

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1652](https://fecgov.atlassian.net/browse/FECFILE-1652)

**Comment by PaulClark2** [comment]
The hypothetical I presented was a new was filed using v8.2 and the amendment will be filed today (v8.4). 

- The amendment must be in v8.4
- Reports filed using out-of-date specs are rejected. 
- FECFile software builds .fec file as per the current format specifications. All fields from previous versions will be mapped to latest version.

**Comment by PaulClark2** [comment]
Once the format specs are finalized and published, we give the vendors 90 days to implement the changes.
