### ISSUE TITLE
Remove styling of old login process

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#111]
Now that we have the new login page, remove the old login styling located in the directory:

src/app/shared/scss

- [x] Unsure new styling still works
- [x] Lower angular.json budgets initial maxiumError to 5mb

**Comment by mjtravers** [comment]
This ticket is on hold until the old login page that is part of the app is still in use.

**Comment by MitchellTCG** [comment]
@mjtravers 
#### There is a small ui change
<img width="944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXU1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--690589eabcdae0388bdc25127ef6fbe8005cc8ca/Screenshot%202024-03-06%20at%2010.00.08%E2%80%AFAM.png" alt="Screenshot 2024-03-06 at 10.00.08 AM.png" />


PASSED QA
