### ISSUE TITLE
Create python script to generate basic Django model for SA from fecfile-Validate SA schema

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#12]
Create a generic python script in the fecfile-web-api/bin directory to create a basic Django model for the Schedule A transactions.

**Details**
- Use the Schedule A spec from https://docs.google.com/spreadsheets/d/1jZLQWVvXgzpST4bP7tn3SlovUf4pC16e
- Base code on this open source script: https://gist.github.com/radzhome/d3b1586b8009ff8e1758cba6a3d92acf
- Place script in fecfile-web-api:/bin directory
- Get SA schema from here: https://github.com/fecgov/fecfile-Validate/tree/data-dictionary/schema
- Validation and aggregation of model fields will be covered in a future ticket
- The resulting script should be generic enough to also create models for the other schedules and forms.

**Acceptance Criteria**
- [x] A script that performs the creation of the boilerplate code
- [x] Basic CRUD operations from model to new database table: SA_transactions
- [x] Table has additional tracking columns. Additional columns TBD by inspection of existing sched_a table
- [x] Unit tests for basic CRUD operations
- [x] Inline documentation following Google-style documentation standard
- [x] Informative logging for future debugging to STDOUT
- [x] Model property names must match SA schema property names or have an easily identifiable link

**Comment by AureliaKhorsand** [comment]
**Backlog Grooming 1/20 Notes**: No validation in scope. Todd confirmed there is no web page in scope of this ticket, but it can be added later. Goal is to automate as much as possible so it can be replicated on other Schedules.

**Comment by toddlees** [comment]
fields missing from current model are:
`report_id
entity_id
create_date
last_update_date
levin_account_id
aggregation_ind`

and maybe `purpose_description`

**Comment by toddlees** [comment]
Ready for CR.

**Comment by toddlees** [comment]
QA:
Here is the [script](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/scripts/json_schema_to_django_model.py)
Here is the [model](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/scha_transactions/models.py) produced by the script

**Comment by WiseQA** [comment]
Reassigned to @mjtravers for Code Review.   Please provide links to Unit tests for basic CRUD operations as stated in Acceptance Criteria.  Also what is the script link provided above ?  There are a lot of references in the acceptance criteria.

**Comment by mjtravers** [comment]
@toddlees Todd, see Shelly's comments above. Assigning ticket to @toddlees and sending to In Progress

**Comment by toddlees** [comment]
- [Script](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/scripts/json_schema_to_django_model.py)
  - **A script that performs the creation of the boilerplate code**
  - **Inline documentation following Google-style documentation standard**
- [Model](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/scha_transactions/models.py)
  - **Basic CRUD operations from model to new database table: SA_transactions :** CRUD operations come from implementing the django model
  - **Table has additional tracking columns. Additional columns TBD by inspection of existing sched_a table:** We added `created` and `updated` fields to track events
  - **Model property names must match SA schema property names or have an easily identifiable link**
- [Unit tests](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/scha_transactions/tests.py)
  - **Unit tests for basic CRUD operations**
- [Logging](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/scha_transactions/signals.py)
  - **Informative logging for future debugging to STDOUT**

**Comment by mjtravers** [comment]
moving to QA

**Comment by toddlees** [comment]
unit tests passed: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/114/workflows/8ca81e4e-ecaf-4691-9ac2-9cea4f1c4c00/jobs/276/steps

**Comment by WiseQA** [comment]
Verified unit test passed successfully see below:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/30837734-15f8-4bbf-b019-b2cdfd942b14)

Detailed links above to verify Script, Model and Logging.

QA review completed.  Moved to Stage Ready.
