### ISSUE TITLE
Refactor sorting of report code column on report list page

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#123]
### Business Reason ### 

As a user viewing the Report list page, I want to be able to sort on report code labels.

### Acceptance Criteria ### 

When sorting the reports list table by report code, the rows sort properly

### Tech Notes ###
Based on decisions from the 5/23 weekly dev meeting, the report code labels are to be stored in a Django model in the Django f3x_summaries app. The api will use the model table in its query sort for the reports table and also provide an endpoint for the front end to pull the labels via a REST endpoint.

Files of interest:
- https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/f3x_summaries/views.py#L18-L45
- https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/shared/models/f3x-summary.model.ts#L81-L109
- https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/reports/report-list/report-list.component.html#L62

**Comment by WiseQA** [comment]
Put back into Code Review - the Unit Test needs to show Pass / Fail, like example was given.   @toddlees assigned back

**Comment by Elaine-Krauss-TCG** [comment]
The unit tests do show that they passed?  Right at the top on the page that I linked to before moving it to code review.  Looking over the [example](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-validate/4) given by Todd again, I still don't see a meaningful difference between what I did and what was done there by the person who handled that ticket.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c29c0d04-7358-4c9e-808a-73773d48cfd0)

**Comment by WiseQA** [comment]
Okay I am good with it - was just verifying - go ahead and move back to my
bucket Elaine -
Who did the CR ?


*Shelly Wise*
*QA/Test Engineer*
*Tygart Technology*
***@***.*** ***@***.***>*
*304-657-9070*
*CMMI - ITIL - ISO 9001:2015 - Agile/SAFe*

**Comment by Elaine-Krauss-TCG** [comment]
Alternative link to the [CircleCI Results](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/639/workflows/f646c3d4-0a7c-4ce6-a567-dfcf9d8af449/jobs/2323)

**Comment by WiseQA** [comment]
Verified unit test passed successfully, visual inspection.
QA review completed.  Moved to Stage Ready.
