### ISSUE TITLE
WebService Worker: cloud.gov setup

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#153]
We need to be able to run a celery worker whose task is developed in the fecfile-web-api repo.

## Tasks ##
- Create cloud.gov manifest to spin up a Cloud.gov application
- Start celery worker in cloud.gov DEV space (see bin/run.sh and Procfile)
- Add Redis, S3, and Postgres resources to the Cloud.gov api and worker manifest files
- Update tasks.py to include the deployment to the celery cloud.gov service space.

## Acceptance Criteria ##
- Screenshot of cloud.gov dashboard with Celery service operating:
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/ab5ea977-edb8-4066-acce-738901dcc37b)
- Screenshot of cloud.gov dashboard with Redis, S3, and Postres services attached
`Elasticache Redis Broker` is Redis, `Relational Databases` is Postgres
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/65b99540-471a-45a6-a1d2-7b3539659b08)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA Visual inspection completed per DEV screenshot above. 

QA review completed.  Moved to Stage Ready.
