### ISSUE TITLE
WebService Worker: System to send *.fec file with metadata to WebUpload service

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#163]
### Dev Notes ###
This task will send both the .FEC file, (one stored in S3 and written by the web services #341, #342) and added metadata. **This task will start when the endpoint created in #291 is called.** Developer will create a web service to pull the .FEC from S3 and to collect the metadata from the fecfile api db.  The web service will then submit the .FEC file and metadata to WebUpload and store the response from FEC into the web services result backend (redis).

Complete list of metadata to be sent to FEC along with *.fec file is as follows:
- Committee ID
- eFiling Password
- Email_1
- Email_2
- Agency ID _(use FEC; see testing notes in comment)_

NOTE: THE VPN LIST BELOW ARE SEPARATE TASKS TO BE DONE IN COORDINATION WITH FEC STAFF AND OUTSIDE THE SCOPE OF THIS TICKET
Steps to get access to test server in side VPN:
- [x] Get approval from Ken and Drew
- [ ] Contact Scott to make test-docquery link public
- [ ] Put information for testing into this ticket

Dev Note: "Date Signed" in specifications will be the date the user submits from FECFile Online.

### QA Notes ###
This ticket will be QA'ed at the QA demo on Monday (8/15) with screenshots
BEFORE SUBMITTING: change the email in the `Confirm Information` tab to your email address because FEC will email whatever address is there and we want to avoid emailing real people.

**Comment by AureliaKhorsand** [comment]
Note: Ticket needs information on test server so that QA can test that we sent appropriately. Will add to ticket once received ( @lbeaufort currently researching)

**Comment by mjtravers** [comment]
1.       Register as a New Vendor using the below link in test environment (Need FEC VPN to access)

a.       https://test-efilingapps.fec.gov/registration/vendorregistration.htm

b.      Use below API key if you are unable to create one. I just created one for TCG

4ac854dd46c804b96f8fba61c21bfc5a07calHnZ

2.       Create a Test Committee using below link(Ryan can help creating new ID’s)

a.       https://test-webforms.fec.gov/webforms/form1/index.htm#

3.       Create a password for the committee ID’s using the link below

a.       https://test-webforms.fec.gov/psa/index.htm

4.       Once you have the “.FEC” file ready you can upload the reports to the Test Server(Agency ID:  FEC)

a.       For manual validating , printing  or upload please use the link below

                                                               i.      https://test-efoservices.fec.gov/

b.      To consume the API please check the help section for the endpoints(Agency ID:  FEC)

                                                               i.      Web Print https://test-efoservices.fec.gov/static/webprint_help.html

                                                             ii.      Web Check https://test-efoservices.fec.gov/static/webcheck_help.html

                                                            iii.      Web Upload https://test-efoservices.fec.gov/static/webload_help.html

5.       Once a filing is uploaded you can see the RAW Filings here (Need FEC VPN to access)

a.       (HTML) https://test-docquery.fec.gov/cgi-bin/forms/C00807859/

b.      (.FEC File) https://test-docquery.fec.gov/dcdev/posted/7787894.fec

c.       (.pdf) https://test-docquery.fec.gov/cgi-bin/fecimg/?C00401224

d.      (.csv) http://test-docquery.fec.gov/csv/894/7787894.csv

**Comment by mjtravers** [comment]
Passes CR, sending to QA

**Comment by MitchellTCG** [comment]
![Screen Shot 2022-08-16 at 1.43.05 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e285c3f0-afef-49c7-8730-4cbb001eb229)

![Screen Shot 2022-08-16 at 1.48.53 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a4d37f07-aa8b-4899-a51f-8ba1ee22f1cf)

![Screen Shot 2022-08-16 at 1.58.56 PM.png](https://ima![Screen Shot 2022-08-16 at 1.59.33 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0f09b341-eeb9-4c62-bb43-fe9cf2d0fdf0)ges.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b754dda3-2c22-413c-b243-c658bfdd9437)

**Comment by WiseQA** [comment]
QA "Visual" Inspection Complete.  Reference screenshots above.   Moved to Stage Ready.
