### ISSUE TITLE
Defect - Report dates can overlap when new report dates are outside existing report dates

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#173]
### Business Reason ### 

Defect - As a user, I will be able to get a warning when I enter a report period that is outside and existing one so that I don't have overlapping reports.

### Acceptance Criteria ### 

**If** I have a Form 3X with a date 7/1/2022 - 7/31/2022
**When** I enter a new Form 3X with the period of 6/30/2022 - 8/1/2022
**Then** a  warning will show up on the reports page telling me that I have an overlapping report date

### Notes ### 
This defect encompasses 2 errors:
1.  Form 3X report period is outside existing one (as stated above).
2.  QA adhoc testing during Sprint 11 the Covering Period "From" "To" dates are required fields. @MitchellTCG @mjtravers per discussion adding this issue to this ticket. Covering period "From" "To" date fields are broken, to where no dates have to be entered.

Defect found in Sprint 10 and Sprint 11.

**Comment by AureliaKhorsand** [comment]
@mjtravers @MitchellTCG is this a defect from #294? If so, should it be marked as such?

**Comment by WiseQA** [comment]
@Aurelia Khorsand ***@***.***> @Mitchell Jarrett
***@***.***> @Matt Travers ***@***.***> this was
discussed and is not a defect from ticket #294.  We met what ticket #294
was showing and that ticket was signed off on.

*Shelly Wise*
*QA/Test Engineer*
*Tygart Technology*
***@***.*** ***@***.***>*
*304-657-9070*
*CMMI - ITIL - ISO 9001:2015 - Agile/SAFe*

**Comment by AureliaKhorsand** [comment]
@mjtravers @MitchellTCG @WiseQA Can we document here how this isn't a defect from #262? (Sorry, I wrote the wrong ticket number in my original comment). It seems like the AC from #262 should cover this.

Also, why is this in API repo?

**Comment by WiseQA** [comment]
Screenshot of Report Dates.   Example of issue is not "true dates" being used (e.g., August 20 (M8) monthly report coverage dates are 06/01/2022 - 06/29/2022.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a891ed08-ae64-424b-bf00-abe2bca8f0e5)

The overlapping dates for July 20 (M7) monthly are shown in screenshot.  These 2 issues should be this ticket from previous discussion.

**Comment by mjtravers** [comment]
I am marking this ticket as a defect to distinguish it from BA generated tickets as it is a bug found by the devs rather than a requirements generated ticket.

**Comment by WiseQA** [comment]
QA adhoc testing during Sprint 11 the Covering Period "From" "To" dates are required fields.  @MitchellTCG @mjtravers per discussion adding this issue to this ticket.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/24e72470-31f1-4c49-8ffc-4b2e5cca075b)

Once saved report with no dates, report displays in manage reports without coverage dates.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bec48698-7d99-40ae-98de-578bc0ca400e)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review and testing of overlapping dates passed (see screenshot).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d60deb7f-8546-4664-80a3-cd6c21cb68a8)

Second issue of this defect fails.   Covering period "From" "To" date fields are broken, to where no dates have to be entered.  (see above screenshots).

Returned in "In-Progress" for date fix.  @MitchellTCG @mjtravers

**Comment by Elaine-Krauss-TCG** [comment]
On local, the fields are required as expected.  The angular "required" validators  are already [included](https://github.com/fecgov/fecfile-web-app/blob/develop/front-end/src/app/reports/f3x/create-workflow/create-f3x-step1.component.ts#L104-L105)

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/61dc4537-6af8-4181-abc6-8462955efd82)

**Comment by Elaine-Krauss-TCG** [comment]
On further review, the fields seem to lose their required validator if the report type is changed?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA review verified Second issue of this defect fails. Covering period "From" "To" date fields are broken, to where no dates have to be entered.

Covering period "From" "To" date fields are "Required Fields" and cannot save report.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2e19b97f-ca70-495f-bfd2-ee288ed7c9e3)

QA review completed.  Moved to Stage Ready.
