### ISSUE TITLE
Use Transaction Type Schema In Validation

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#175]
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/a850496e-8b3b-412e-96f8-25a9b7225131)The API should require `transaction_type_identifier` to be defined in a Schedule A Transaction for creation.  It should also use the value of `transaction_type_identifier` to determine which schema to validate against.  Currently you can submit an INDV_REC transaction without defining `contributor_city` or other fields that aren't required in the base SCHA schema.  This should throw a validation error because the INDV_REC requires `contributor_city`.  It does not because SCHA allows it to be undefined.

See below how a request missing `contributor_city` is successfully saved and does not throw an error.
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/ed765fe5-1aa2-46a6-b588-d435d59acee3)

### Acceptance Criteria ###
1. `transaction_type_identifier` must be required in all transaction requests
2. based on `transaction_type_identifier`, the correct schema must be used to validate the transaction.

**Comment by AureliaKhorsand** [comment]
@toddlees is this at all relevant to the transaction type identifier conversation we had today? (Updating the names to make more sense?)

**Comment by AureliaKhorsand** [comment]
@toddlees is this ticket still relevant?

**Comment by AureliaKhorsand** [comment]
@toddlees bumping again. Is this still relevant?

**Comment by mjtravers** [comment]
This ticket is OBE. The validation in the back end is throwing an error on both a missing transaction_type_identifier and  a missing contributor_city. See screenshot:
<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFp2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dab62e5d1d8ccf078c060debc15d746001167ed/image.png" alt="image.png" />


Closing ticket.
