### ISSUE TITLE
Update Report Type label for "JULY 31 (MY)" on Mange Reports

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#188]
It was discovered that the STAGE server database had the wrong label for the "MY" report type. A new migration needs to be created to ensure the label in the report_code_labels table for the report_code = 'MY' is set to 'JULY 31 (MY)' so that update will be deployed on DEV.

## Acceptance Criteria ##
When viewing the Report Type for a "MY" report, I will see the text "JULY 31 (MY)" in the "Type of report" column of the reports table

**Comment by WiseQA** [comment]
QA Review Completed.  Verified label change.

Moved to Stage Ready
