### ISSUE TITLE
System to order transactions in *.fec file by schedule, line, and date order

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#194]
### Business Reason ### 

As a FECfile administrator viewing my report as a *.fec file, I will be able to view the transactions in the order listed below in the acceptance criteria so that I can view the transactions in a logical order to help in reporting and supporting the data in the report.

### Acceptance Criteria ### 

**Given**  I am a FECfile administrator
**And** I am viewing my report in my *.fec file
**Then** I will see the transactions in lexicographically ascending order:

1. Within a report, by **Schedule**
2. Within a schedule, by **Line Number**
3. Within line number, **by order transaction was created**
4. And child transactions be displayed directly after the parent in the order in which they were created **only if it is in the same schedule.** If the associated transaction is in a different schedule, it will be listed within that schedule following the rules above.

#### DEV Notes
- For testing purposes we need to add the date/time created into the specification *temporarily*. Once the ACs pass QA, then must remove date/time created.
- This may affect the default order of the front-end table, which is acceptable.
- Testing info in .fec has been feature flagged to `OUTPUT_TEST_INFO_IN_DOT_FEC`.  Currently dev/fecfile-web-services is the only instance on cloud.gov with this setting activated.

#### QA Notes
- For testing purposes, date/time created will be added temporarily added to the specification in the *.fec file. Once this ticket passes ACs, inform developers and retest to ensure specification is as expected. 
see example below of test info in parenthesis![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/803cf464-62df-4289-b7ac-a3407b62f4da)

**Comment by toddlees** [comment]
@AureliaKhorsand @GreggMoreland 
what order are we sorting schedules and line numbers(actually an alphanumeric starting with a letter) in?

My guess would be [lexicographically ascending order](https://tools.knowledgewalls.com/online-lexicographic-ascending-or-descending-sort)?

**Comment by AureliaKhorsand** [comment]
@toddlees correct - thanks for clarifying (and teaching me a new word!) I've updated the ACs to reflect that.

**Comment by AureliaKhorsand** [comment]
Note: The ACs were updated on 2/13/23 during PI 5 planning, specifically number 4. FEC clarified that child transactions that are on a different schedule should be listed in the appropriate schedule, NOT beneath the "parent" transaction if it's on a different schedule. This is a change in requirements from the 1/10/2023 requirements meeting.

**Comment by toddlees** [comment]
configured dev/fecfile-web-services to have OUTPUT_TEST_INFO_IN_DOT_FEC set to true.  This means dev will produce .fecs that will not be submittable until we revert this setting

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by toddlees** [comment]
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/b3ff1e32-4ab1-4cb0-81cf-5ed808820514)

**Comment by WiseQA** [comment]
QA review verified with DEV as a visual the .fec file is by schedule line and order by date transaction was created as denoted above and below screenshots.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/483e3039-a981-42e9-9c4f-d7c0c8039655)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8336fa0e-34f3-42ab-93d0-0148df3bd096)

QA Review Completed.   Moved to Stage Ready.
