### ISSUE TITLE
Upgrade Django to version 3.2 LTS

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-api#2]
fecfil-online/django-backend is currently using Django version 2.2. This should be upgraded to version 3.2 to maintain compliance with the QASP standard of being at most one major version behind the latest release.

**Acceptance Criteria:**
- [x] Unit tests that pass before the upgrade also pass after upgrade.

**Comment by WiseQA** [comment]
Compared the number of failed tests in the front-end end-to-end before (11 failed) see below:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7b843eaa-34e8-44e5-980e-ca7eeec2017d)

**Comment by WiseQA** [comment]
Compared the number of failed tests in the front-end end-to-end after (2 failed) see below:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0460df1d-3640-4e8d-b01c-7c633fef8215)

Revisit front end end-to-end testing once environment up and running.  QA review completed.  Moved to Stage Ready.
