### ISSUE TITLE
Fix leak in Git Secrets scan rules

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#203]
Update regex patterns for Git Secrets tool to cover leak show below. [Custom Git Secrets rules](https://github.com/fecgov/fecfile-web-api/blob/main/install-git-secrets-hook.sh)

[Click here to see code that slipped past the Git Secrets screener](https://github.com/fecgov/fecfile-web-api/blob/06f1b2bce3c08763bd940d315e74b9b5dbdbe686/django-backend/fecfiler/web_services/tasks.py#L46-L47)

**QA NOTES**
The QA for this ticket is screenshot verification. See the screenshot provided by Elaine in the ticket comment dated Sept. 8 at 11:48am

**Comment by Elaine-Krauss-TCG** [comment]
Updates one of the git secrets patterns to be much more robust:
```['`"]?(dbpasswd|dbuser|dbname|dbhost|api_key|apikey|password|user|guid|hostname|pw|auth)['`"]?\s*[=:]\s*['`".,:\w\/\\+!@$%^&*~?()\[\]{}=-]{4,120}```

**Comment by Elaine-Krauss-TCG** [comment]
Patterns work locally on a test file
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/ca484052-c3ae-473f-9d51-b7dbe05bf37f)

**Comment by WiseQA** [comment]
QA Verified by inspection per DEV.

QA Review Completed.  Moved to Stage Ready
