### ISSUE TITLE
Upgrade Django to 4.1

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#207]
Upgrade Django to 4.1

The current package will be removed as it is not longer supported.

Dev Notes:
1. Research impact of removing this package and come up with alternatives needed by e2e to discuss with the dev team before proceeding with fix. Basically figure out a secure way for e2e tests to log in and run.
2. Once upgrade is completed, remove exceptions from the api .safety.dependency.ignore file

## Acceptance Criteria ##
- API unit tests run successfully

**Comment by Elaine-Krauss-TCG** [comment]
Upgrading Django to 4.1 currently requires replacing the `djangorestframework-jwt` package with something that is still being actively updated.  

After talking with David & Todd, it seems that we might not need JWT at all once the old login method has been phased out.

With that in mind, API ticket #207 seems to require further review before it sees further development.

**Comment by mjtravers** [comment]
The djangorestframework-jwt package is not going to get an update. The latest version 1.110.0 was released in June 2017. Seeing as the old login method is not going to be phased out because it is being used by the cypress e2e tests, a replacement package or other solution needs to be found and implemented.

**Comment by Elaine-Krauss-TCG** [comment]
The requirements.txt file that controls the versioning of packages has been updated to use the latest version of all packages.  The djangorestframework-jwt package is incompatible with Django 4.1, and it will need to be replaced with the djangorestframework-simplejwt package.

**Comment by Elaine-Krauss-TCG** [comment]
Djangorestframework-jwt related code has been stripped from the server, a few other Django 4.1-related changes have been made, and the server is spinning up successfully.

Logging in, both with Login.gov and the legacy login page, is broken until SimpleJWT is integrated.  There could be other broken elements of the server's API that can't be observed until the ability to log in is restored.

**Comment by Elaine-Krauss-TCG** [comment]
At present, all but two unit tests are passing.  The two failing unit tests are both related to the removed JWT package.

**Comment by Elaine-Krauss-TCG** [comment]
Legacy login now "works" in so much as it tells the client that it worked and gives them a token.  Currently, the API isn't able to decode that token for any subsequent requests.

**Comment by Elaine-Krauss-TCG** [comment]
Legacy login now works.  Remaining tasks:

- [ ] Cleanup settings files
- [ ] Fix unit tests
- [ ] Run E2E tests to look for edge cases
- [ ] Test login.gov

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/8d2639d5-f024-4bf2-9dc7-98a3e43dfa18)

**Comment by mjtravers** [comment]
For QA, here is a screenshot of the API unit tests running successfully for verification.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
