### ISSUE TITLE
Create Django model for F3X

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#21]
Create a Form 3X Django model. Create the initial model using the script created in ticket [API#12](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/12)

**Details**
- Get F3X schema from here: https://github.com/fecgov/fecfile-validate/tree/develop/schema/F3X.json
- Validation and aggregation of model fields will be covered in a future ticket
- Database tablename will be f3x_summaries

**Acceptance Criteria**
- [x] Basic CRUD operations from model to new database table: f3x_summaries
- [x] Table has additional tracking columns: TBD based on final columns of sa_transactions table
- [x] unit tests for basic CRUD operations
- [x] Google-style code documentation
- [x] info and debug logging
- [x] Model property names must match F3X schema property names

**QA**
[Here](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/163/workflows/5a0f81c0-e48a-41d4-99ce-01ccbafa2822/jobs/403) is the report generated by the automated tests to confirm new code passed the checks.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/2/22:** Pointed at 5.

**Comment by toddlees** [comment]
Ready for CR
https://github.com/fecgov/fecfile-web-api/pull/46
https://github.com/fecgov/fecfile-validate/pull/36

**Comment by WiseQA** [comment]
Verified unit test passed successfully see below:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3726cdc6-582c-4365-a490-cf60e455fdb5)

QA review completed.  Moved to Stage Ready.
