### ISSUE TITLE
[SPIKE] Schedule B technical research and preparation

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#235]
**This ticket is to lay the groundwork for starting Schedule B. Tasks include:**

1. Add Schedule B and Schedule B transactions to the Data Dictionary as a starting point for review. [Here ](https://docs.google.com/spreadsheets/d/1lh8t1cOo1KiCWLbBKCU01AFKPfT5EoKY/edit#gid=1126459094)is the phase 1 spreadsheet for Disbursements that they were using that you may be able to pull from. 

2. Organize Data Dictionaries with a "Table of Contents". I thought it may be best to have Forms > Schedules > Transactions, but there are some transactions that may be on multiple forms (for example, 3X, 3P, and 3L share a lot, I believe). Would we be able to have one transaction under multiple forms if we organize it this way?

3. Develop "Schedule prep" checklist that includes what must be done before we begin developing each new schedule/form

**QA Notes**
1. Verify data dictionary layout has been updated to show sections for Receipts and Disbursements (Disbursements is empty for now) See here for dictionary: https://fecgov.github.io/fecfile-validate/
2. Confirm that the SchB has an entry in the data dictionary table section Forms & Schedules
3. See "Steps for setting a new Schedule" in comments below to confirm "Schedule Prep Checklist"

**Comment by AureliaKhorsand** [comment]
**Steps for setting a new Schedule**
	1. [BA] Create Master Transaction Tab/List.
	2. [BA] Create "Spec Updates [WIP]" spreadsheet, with each transaction on its own tab for review. Use the Vendor sheet.
	3. [DEV] Dev will scrape the Spec Updates sheet using Python for grouping the transactions (internal groups).
	4. [BA] Put the internal groups into the Master Transaction sheet.
	5. [BA] Choose one transaction for each group to be the sample group ticket.
	6. [DEV] Add Schedule and Schedule transactions to the Data Dictionary.

**Comment by WiseQA** [comment]
QA Review completed by DEV input.
QA review completed.  Moved to Stage Ready
