### ISSUE TITLE
Add "AGGREGATION GROUP" to transaction schema

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#237]
**Dev Tasks:**

**For every Transaction**

- [x] Validate: add "AGGREGATION GROUP" underneath "CONTRIBUTION AGGREGATE" row

- [x] Validate: This field is required.

- [x] Validate: Add const parameter containing the aggregate group ID for the transaction type

- [x] API: Create a Django migration to add the aggregtion_group column to the scha_transactions table

- [x] API: Update Django scha_transactions model to include the aggregation_group field, the field should be required

- [x] Front end: Update the SchATransaction model to include the aggregation_group field property

- [x] Front end: Update the existing TransactionType interface and associated TransactionType models to include the aggregation_group and set each model aggregation_group field to the appropriate aggregation group tag (e.g. "General")

**Comment by Elaine-Krauss-TCG** [comment]
Changes to the validator, API, and app are all in place.

Verified that the user is able to create transactions of each type
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/8f69e99f-f43f-422c-bdc3-b6ea99edc576)

**Comment by Elaine-Krauss-TCG** [comment]
[Validation PR](https://github.com/fecgov/fecfile-validate/pull/120)
[App PR](https://github.com/fecgov/fecfile-web-app/pull/610)
[Api PR](https://github.com/fecgov/fecfile-web-api/pull/240)

**Comment by mjtravers** [comment]
From CR, some changes are quested regarding using types and enums on the front end and using all caps and underscores for the aggregation group identifiers. Sending back to In Progress

**Comment by AureliaKhorsand** [comment]
@Elaine-Krauss-TCG @mjtravers has this been updated to have the aggregation groups in all caps and with underscores? It may be a good idea to have a screenshot with the end-state

**Comment by Elaine-Krauss-TCG** [comment]
Yes
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/cc11b1c5-c240-4f1a-80be-7ce39807dad4)

**Comment by WiseQA** [comment]
QA Visual Inspection completed per DEV..   

QA Review Completed.  Moved to Stage Ready.
