### ISSUE TITLE
Rotate `SECRET_KEY` DEV/STAGE/PROD

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#27]
Business Reason 

As a developer, I must rotate the `SECRET_KEY` because it was previously hard-coded, which is a security vulnerability.
 The SECRET_KEY is a Django setting we set via the credentials service in Cloud.gov

 Tech Notes 

*   [x] Generate separate keys for each environment

### QA Notes ###
 
  
 null

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

**Comment by MitchellTCG** [comment]
This will be dependent on #26

**Comment by mjtravers** [comment]
No code to review and no screenshot possible as the information changed is private.

For QA: Verified that users are able to log into DEV, STAGE, and PROD.

**Comment by WiseQA** [comment]
Per DEV no code review for the SPIKE.   QA is able to login to DEV, STAGE and PROD.  No further QA review on this ticket.

Moved to Stage Ready.
