### ISSUE TITLE
Create Sched B Django app

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#287]
Similarly to the scha_transactions app, a schb_transactions app needs to be implemented in the Django API

**Tasks**
1. Create schb_transactions app with associated python files and validation. Use scha_transactions as a template. Create a primary transaction app that the scha and schb will be moved into as a sub app. With this setup common code can be located in the transaction app.
2. Refactor scha_transactions in conjunction with the development of schb_transactions to pull common code and methods out to either a parent class or mixin classes. This includes separating out the contact and memo_text payload handling in the serializer.

**Acceptance Criteria**
GET and POST/PUT REST endpoints work with validation

**Comment by mjtravers** [comment]
E2E test result report. Here is the report output for the tests run on the code for this ticket:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/2aa3b595-a826-4357-998f-4ffa8d18d115)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA Review consisted of visual inspection of E2E test result report provided by DEV for this ticket.  

QA Review Completed.   Moved to Stage Ready.
