### ISSUE TITLE
Refactor transaction child update to not delete missing children

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#288]
In the scha_transaction serializer, the update() method deletes transaction children that are missing from the payload. This is not necessarily intuitive for the use of the endpoint so remove this functionality so that children in the payload are created or updated but NOT deleted.

**Acceptance Criteria**
When saving a transaction to the backend whose payload is missing a child transaction that exists in the database, that child transaction is not deleted from the report.

**Comment by Elaine-Krauss-TCG** [comment]
The functionality that this ticket would address is being caught in the work being done for #287

**Comment by toddlees** [comment]
This ticket is still valid.  The code was written while working on #287 and will be deployed to dev along with #287 to test

**Comment by mjtravers** [comment]
E2E test result report. Here is the report output for the tests run on the code for this ticket:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/baff91c9-b17b-4856-b90e-0fff35d7306b)

Certain tests will be run again after the completion of [app#320](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/320) since the bug impacts the saving of memo transactions.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA Review consisted of visual inspection of E2E test result report provided by DEV for this ticket.  

QA Review Completed.   Moved to Stage Ready.
