### ISSUE TITLE
Set up API rest endpoint online documentation

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#29]
### Business Reason ### 

The `django-rest-swagger` package is no longer supported, and is not compatible with Django 3.x. When we upgraded to Django 3.x, we broke the API documentation. 

See https://fecfile-web-api-dev.app.cloud.gov/api/docs
and https://github.com/marcgibbons/django-rest-swagger/issues/832 and https://github.com/marcgibbons/django-rest-swagger/issues/815

*Task* Install the [drf-spectacular](https://github.com/tfranzel/drf-spectacular) python package and configure for use in fecfile-web-api

As a developer, I will be able to get access to the fecfile REST API via my browser so that I can have access to documentation describing the REST endpoints

### Acceptance Criteria ### 

- [X] When I go to this link https://fecfile-web-api-dev.app.cloud.gov/api/docs, I see a UI that lets me explore the fecfile API
- [X] Pingdom alerts are set up to check API documentation

### QA ### 

- [x] When I go to this link https://fecfile-web-api-dev.app.cloud.gov/api/docs, I see a UI that lets me explore the fecfile API

**Comment by WiseQA** [comment]
Verified link https://fecfile-web-api-dev.app.cloud.gov/api/docs, that an UI is seen and lets me explore the fecfile API:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0bd2a2f4-cbbc-437e-b229-429f59b7e880)

QA review completed.  Moved to Stage Ready.
