### ISSUE TITLE
Add uptime monitoring 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#30]
### Business Reason ### 

As a developer, I need to be notified when an application goes down so that I can fix it.

**Technical considerations**

Consider Pingdom? It's unclear exactly how many checks remain on our current plan, so we may need to increase our plan size or explore other options. Looks like we can purchase a bundle of 10 more alerts for $10/month extra.

### Acceptance Criteria ### 

- Alert sent to #fecfile-alerts slack channel if web-app or web-api are offline.
- Pingdom set up for web-app and web-api for dev, stage, and prod Cloud.gov spaces.
- The URL for the web-api endpoint for Pingdom to test is: https://fecfile-web-api-dev.app.cloud.gov/api/v1/core/sample_sql_generate

**Comment by lbeaufort** [comment]
Here's the ticket to add Pingdom account policies and access: https://github.com/fecgov/fecfile-accounts/issues/12

**Comment by lbeaufort** [comment]
Pingdom alerts are here: https://my.pingdom.com/app/newchecks/checks


We did a team demo of the alerts. @todd will let me know when the API reorg work is done so we can set up a Pingdom maintenance window and modify the API check to look at the docs endpoint when that work is done.

**Comment by WiseQA** [comment]
Demo completed, QA review completed.  Moved to Stage Ready.
