### ISSUE TITLE
Create a database table for the transaction app

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#316]
In the Django app created in ticket [#287](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/287), create a database table for the app that will contain the core information of all current and future transaction types. These will initially be:

form_type
filer_committee_id_number
transaction_id
transaction_type_identifier
itemized

Additional columns may be necessary for parent, contact, and memo_text relations

### QA Notes ###
See passing unit tests in comments below.

**Comment by toddlees** [comment]
Unit tests passing
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/570edaa1-50a0-43df-8c52-7ecff44d8cc9)

**Comment by toddlees** [comment]
Screenshot of accessing fields from transaction record
form_type
filer_committee_id_number
transaction_id
transaction_type_identifier
itemized
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/959f8989-66bd-4490-9b44-e529a504324c)
