### ISSUE TITLE
Bug: "Save and add another memo" button throws an error

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#320]
When adding a memo and select "Save and add another memo" button I get the following error.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1fec4ec0-42d5-405b-8532-7767a8643790)

This bug has been traced to changes made in [api#287](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/287) and will be corrected in [api#316](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/316).

This ticket is to verify issue has been resovled since it is impacting other tickets.

**Comment by mjtravers** [comment]
The initial bug fix provided by @toddlees allows the child transaction successfully save with "Save and add another memo" but there is still an issue where subsequent GETs to the child transaction return a payload without its parent. One side effect is that the "Associated With" column in the Transactions table is blank when it should have the transaction id of the parent.

Sending ticket back to In Progress for more work.

**Comment by MitchellTCG** [comment]
![Screenshot 2023-01-24 at 8.42.36 AM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/439da41b-be53-4fb9-b4ea-09aede670372)

I get this error message when I try to edit a Parent Transaction of a Memo. 
IS THIS ISSUE RELATED TO THE DJANGO PROBLEM

**Comment by MitchellTCG** [comment]
Please see if this bug is affecting: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/347

**Comment by mjtravers** [comment]
Passes CR and smoke testing on DEV. Ready for QA on DEV.

**Comment by WiseQA** [comment]
QA review retested "Save & add another memo" is broken.   

@mjtravers @MitchellTCG returned to In-progress for fix.

**Comment by toddlees** [comment]
removes `Save & and add another memo` button when editing an existing transaction to match our existing design pattern ([#362](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/362))

button will always work as expected now.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Additional bug found and denoted in this ticket.
