### ISSUE TITLE
Investigate "crash" log entries in PROD Kibana logs

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#337]
While investigating a Pingdom alert that PROD was down on Jan 31, 20023 at 2:33pm, it was noted that there are a number of "crash" log entries in the Cloud.gov Kibana logs for the PROD api service.

The task is to use app and Kibana logs to determine and eliminate the frequent crash states of the PROD api service.

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 null

**Comment by Elaine-Krauss-TCG** [comment]
In the last year there have been 328 crash log entries (as found by searching for "crash" within the message field) between all three spaces (DEV, Stage, and Prod).  Of these, 29 log entries are specific to Production, and all 29 are dated to 05/22/2024.  Other attempts at finding crash-related log entries were made, but none were found.

![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/52cea39b-33d0-4ea9-b1d6-3b4edc92daf0)


The query used:
```{
  "query": {
    "query_string": {
      "default_field": "@message",
      "query": "*rash*"
    }
  }
}```

All crashes involved the API crashing with the message `Process has crashed with type: "web"`

Trying to view the full document for any of these errors yields the following error:
![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/4ebd5845-c1cb-44dc-bb8c-bd7bf43520ba)

This might be the result of my inadequate understanding of Kibana/Elasticsearch or there might be an issue with our Kibana configuration.

**Comment by mjtravers** [comment]
No code to review for this ticket. Results of ticket discussed in comments above. Sending to QA.

**Comment by WiseQA** [comment]
Per DEV no code to review for this ticket.  

QA Review Not Needed on this ticket. Moved to Stage Ready.
