### ISSUE TITLE
Add Schedule C to the *.fec file generate code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#346]
Add the Schedule C transactions to the generated *.fec file in the Django backend so that they are included in the WebUpload and WebPrint submissions.

**Tasks**

- Add the Schedule C definitions to the web_services app
- Add SchC.json file to the dot_fec/schema_fields directory

**QA Notes**
There is no way to enter Schedule C data yet from the front-end so only testing available are the API unit tests. Screenshots and links to successful unit tests are in the ticket comments below.

**Comment by mjtravers** [comment]
Passes unit tests:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/b9ae9b11-4d45-4e5c-bf89-c6d06c97371a)

CircleCI test run: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/1734/workflows/be7b6303-f2b1-424a-ac38-048b3adcb12c/jobs/5350

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA Visual Inspection verified unit tests passed per DEV (see above screenshots)

QA Visual Inspection Completed. Moved to Stage Ready.
