### ISSUE TITLE
API to return 404 when no records are found for GET calls

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#347]
When a request for a report or transaction record is made with a GET call or a previous transaction GET call is made, the API service should return a 404 call to the front-end and the front-end should gracefully handle it.

**Tasks:**

- Update API back end for all GET RESTful calls to return a 404 response.
- Ensure call to get previous transaction returns a 404 if not previous transaction found
- Update front-end GET calls to gracefully handle the 404 no record found so that it does not create an error pop up unless not finding a record is explicitly an error

### QA ###
see comment below with unit tests passing

**Comment by toddlees** [comment]
api unit tests pass
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/1618/workflows/ab0f372b-8621-43d3-91a1-ab9cc5520422/jobs/4967
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/0b81a592-d8e0-464a-a367-4def5883e6eb)
app unit tests pass
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/2281/workflows/260e0851-8cf2-4419-afaa-764e711daf1d/jobs/8589
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/f3a19cad-2615-4e06-a957-6f7993f09335)

**Comment by toddlees** [comment]
passes cr moving to qa

**Comment by WiseQA** [comment]
QA Visual Inspection verified unit tests passed per DEV.

QA Visual Inspection Completed. Moved to Stage Ready.
