### ISSUE TITLE
Integrate new first_name, last_name fields in openFEC candidate REST API

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#354]
When pulling the candidate information from openFEC, there is currently just a full name field for the name of the candidate instead of breaking the name into first_name, last_name, middle_name, etc. This is a follow on ticket for [#108](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/108) which will just do a simple parse of the full name field already available. When the first_name and last_name fields are available on openFEC, replace the fullname parse with the first_name and last_name.

The fields that will be available and utilized in our system are: cand_prefix, cand_nm_first, cand_m_nm, cand_nm_last, and cand_suffix

Here is the [openFEC ticket](https://github.com/fecgov/openFEC/issues/5347) tracking the addition of the new fields to the openFEC endpoint for candidates.

Notes from Laura's Feb 21 slack message:

Because we realized paper filed F2's won't have parsed data, my recommendation is now:

- start with parsing first and last name from candidate name using ", " as the delimiter
- :white_check_mark:  enter ticket in openFEC to add candidate_firstname etc
- (tentatively) Laura puts in a PR
- Once the work is complete, modify the FECFile logic to use parsed name fields (candidate_firstname etc) and fall back on parsing  name  ourselves only when the parsed fields are unavailable (IE, paper filers)

<h3>QA Notes:</h3>
To test, you should be able to create a new contact with the candidate lookup using candidate id P80000722.  When you select this candidate, LAST NAME, FIRST NAME, MIDDLE NAME, and SUFFIX will populate per the data received from OpenFEC API:

![image](https://github.com/fecgov/fecfile-web-api/assets/104843885/f311ee56-acc4-4e39-9c02-4f231e139e7f)

**Comment by lbeaufort** [comment]
Thanks to the wonderful @hcaofec, this change has been made and is making its way into production. Dev query: https://fec-dev-api.app.cloud.gov/v1/candidate/H8CA05035/history/?api_key=DEMO_KEY

**Comment by dheitzer** [comment]
@lbeaufort regarding your suggestion in the description to `fall back on parsing name ourselves only when the parsed fields are unavailable (IE, paper filers)`, can you clarify what you mean by unavailable? for example, would we fall back on manually parsing if `candidate_last_name` is missing? Thanks.

**Comment by dheitzer** [comment]
reached out to confirm taking the candidate data with the latest **two_year_period** from the history endpoint.

**Comment by mjtravers** [comment]
Needs more code coverage in the front-end. Sending back to In Progress.

**Comment by dheitzer** [comment]
Reached out in the PR to Laura regarding a potential data issue that Elaine noticed during local testing.

**Comment by dheitzer** [comment]
added more code coverage and confirmed that the issue @Elaine-Krauss-TCG noticed is an upstream data issue.

**Comment by WiseQA** [comment]
QA verified when creating a new contact with the candidate lookup using candidate id P80000722. When you select this candidate, LAST NAME, FIRST NAME, MIDDLE NAME, and SUFFIX will populate per the data received from OpenFEC API.

QA Review Completed.  Moved to Stage Ready.
