### ISSUE TITLE
Change Login.gov timeout to 18 hours on DEV and STAGE

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#385]
We checked with FEC staff and it was ok to change the Login.gov timeout from 15 minutes to 18 hours on DEV and STAGE servers.

**Comment by mjtravers** [comment]
The time for the timeout is set in an environment variable, SESSION_COOKIE_AGE,  in cloud.gov. Currently, DEV and STAGE are set to 18 hours and PROD is set to 30 minutes.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA logged into Login.gov verifying timeout issue 18 hours.    Will login at 1:30 and test at 7:30 am tomorrow morning to verify.

**Comment by WiseQA** [comment]
QA
