### ISSUE TITLE
Bug - Manage Users Table not Populating

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-api#386]
During QA testing the Manage Users Table is not populating and an error code is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6da343d1-e083-4edc-88f1-ead10604458b)

1.  login to https://fecfile-web-app-dev.app.cloud.gov/dashboard
2.  Select "Profile" from the dashboard
3.  Under "Profile" dropdown select "Users"
4.  Manage Users table not populating - error message displayed

(NOTE:   This is broken on both DEV and STAGE environments)

DEV verified that this is a backend API issue.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Bug fix was to restore a url route in the authentication module that had been refactored incorrectly during code clean up in December.

**Comment by WiseQA** [comment]
QA review verified Manage Users Table is populating correctly and bug has been fixed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a182626b-39af-4fbc-8a1e-2a75ff937166)

QA Review Completed.   Moved to Stage Ready.
