### ISSUE TITLE
Install Sphinx code documention tool in fecfile-web-api

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#40]
**Tasks**
- Configure Circle CI to generate Sphinx documentation when code is merged into the develop branch following [this tutorial](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/)
- The output of Sphinx should be in HTML format and written to the /docs/_build/html directory during the Circle CI docs-deploy job and **Not** committed to any branches (except gh-pages in a later step)
- Activate GitPages and configure it to read from the gh-pages branch root directory
- Investigate to see if there is a Sphinx linting validation check to alert the developer if there are formatting problems with the inline documentation (This is satisfied by the docs-build job.  When it fails, the developer knows there is an issue with the inline documentation)
- Set up deploy key in GitHub for CircleCI to use
- Give Circle CI the deploy key
- Double check that “Pass secrets to builds from forked pull requests” is set to its default of “Off” in Circle CI
- Configure circleci doc-deploy job to add the ssh_key

**Acceptance Criteria**
- [When a user goes to the fecfile-web-api [GitHub page](https://fecgov.github.io/fecfile-web-api/), they see online documentation HTML pages for the repo code

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 3/3/22:** Added task to see if there is a Sphinx Linting Validation check

**Comment by WiseQA** [comment]
Verified the HTML pages are up and accessible by clicking on the link provided in the Acceptance Criteria.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/311b0b06-31ee-4921-b36e-e631bdb025d2)

QA visual review completed.  Moved to Stage Ready.
