### ISSUE TITLE
Rename Specification Consolidation Groups for NP Partnership Receipt/Memos

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#403]
**Task:** Update "PARTNERSHIP_NATIONAL_PARTY_RECEIPTS" to "NATIONAL_PARTY_PARTNERSHIP_RECEIPTS", and "PARTNERSHIP_NATIONAL_PARTY_MEMOS" to "NATIONAL_PARTY_PARTNERSHIP_MEMOS" 

### QA Notes
- No front-end changes.

### DEV Notes
- specification [located here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=622262881)
- Update specifications and docs in validate repo
- Update validate hash in api repo
- Update references of to schemas in app repo

**Comment by dheitzer** [comment]
@GreggMoreland confirmed that this should be NATIONAL_PARTY_PARTNERSHIP_ATTRIBUTION_MEMOS

**Comment by dheitzer** [comment]
confirmed with @GreggMoreland that this should instead be NATIONAL_PARTY_PARTNERSHIP_MEMOS

**Comment by mjtravers** [comment]
For QA: automated tests passed successfully:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/fa039f27-6ea3-43ec-bba5-96d12fe61388)

Here's the link to the report: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/3361/workflows/13d5ef2d-c073-4d1a-9532-ffc92572e051/jobs/12297

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with DEV team the visual of test passing.   Up to BA's to verify this update is correct.

QA Review Completed.  Moved to Stage Ready.
