### ISSUE TITLE
System to store linked Candidate for each Committee in Contacts Table

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#410]
**Task:** System to store linked Candidate for each Committee in Contacts Table

### Requirements: 
- This information should be pulled from the FEC database.
- Each Committee will have _one_ candidate that should be stored.

**Notes**
- The system will look to the stored relationship in Contact Management before the FEC database when auto-populating Candidate Information based on Committee ID in transactions such as #869, Refund of a Contribution to a Federal Candidate.
- This is a unidirectional relationship.
- We will NOT be storing committees within candidate contacts at this time.

**DEV notes**

- Refer to this research ticket on how to get the data from the FEC API: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/374
- Create a foreign key in the contacts table back to itself to contain the link from the committee contact record to the candidate contact record. It can be called committee_candidate_link
- If the candidate that is linked to the committee does not exist yet in the FECFile Online DB, create it.

**Comment by AureliaKhorsand** [comment]
@mjtravers please add any dev notes you need and move to ADTQR when complete. Thank you!

**Comment by mjtravers** [comment]
Added dev notes. Moving ticket to ADTQR

**Comment by AureliaKhorsand** [comment]
Will be completed in #1029 and #1031. Copying notes over for posterity, and closing as OBE.
