### ISSUE TITLE
Add Schedule C1 to the *.fec file generate code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#438]
Add the Schedule C1 transactions to the generated *.fec file in the Django backend so that they are included in the WebUpload and WebPrint submissions.

**Tasks**

- Add the Schedule C1 definitions to the web_services app
- Add SchC1.json file to the dot_fec/schema_fields directory

**QA Notes**
There is no way to enter Schedule C1 data yet from the front-end so only testing available are the API unit tests. Screenshots and links to successful unit tests are in the ticket comments below.

**Comment by mjtravers** [comment]
Unit test results for QA: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/1996/workflows/76572803-60c7-44f8-8091-1b956005aedf/jobs/6274

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/06f04efb-0b2b-486c-94af-89c604b9fecf)

QA Review Completed. Moved to Stage Ready,
