### ISSUE TITLE
Change transaction tree traversal to "up the tree" via the parents

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#440]
When a user requests a transaction from the API, we currently provide the transaction and its children (and children's children) on the back-end and provide the transaction parents by making additional API calls from the front-end.

A more efficient strategy is to provide the requested transaction's parent (and parent's parent) by traversing up the family tree rather than the current strategy of providing the children by traversing down the tree. Each transaction returned will contain an array of UUID ids of all the children of the transaction. If the front-end needs one or more of the children, it will have to make separate API calls to retrieve them.

**DEV NOTES**
- Refactor all back-end schedule serializers to only return an array of child IDs rather then the child objects
- Refactor all back-end schedule serializers to return the chain of parent transaction as objects
- Refactor front-end resolver, the generation of the purpose description, and transaction.model.ts to handle pulling child objects when needed to prepare transaction data payloads being sent to the back-end
- Remove obsolete scha_transactions app (was replaced by transactions and transactions/schedule_a apps)

**QA NOTES**
All unit tests passing

**Comment by mjtravers** [comment]
Passing unit tests front end:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4084/workflows/48da6e3f-0ebf-457e-a6c8-0aaeb1397c43/jobs/14734
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0MvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23c0e69b5082160f6503ef4516a7cf9ef0a00489/image.png)

Passing unit tests on the backend:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2577/workflows/b7e4a343-c1e1-4e92-b7f6-a144e7b911f1/jobs/8129
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUMvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8bf1e5dcdac43375d799357acc100abc1a54b16/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection front end unit tests and back end unit tests per DEV.

Passing unit tests front end:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80efc510ffbb63a8d43904bb44c0a782d0701869/image.png)

Passing unit tests back end:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df17e7c79cd383c83f8db202b302f0627aff14ff/image.png)

QA Review Completed.   Moved to Stage Ready (after Sprint 33 review)
