### ISSUE TITLE
Add Schedule D to the *.fec file generate code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#482]
Add the Schedule D transactions to the generated *.fec file in the Django backend so that they are included in the WebUpload and WebPrint submissions.

**Tasks**

- Add the Schedule D definitions to the web_services app
- Add SchD.json file to the dot_fec/schema_fields directory

**QA Notes**
There is no way to enter Schedule D data yet from the front-end so only testing available are the API unit tests. Screenshots and links to successful unit tests are in the ticket comments below.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4b1b284a-048c-4596-be74-0568f97412cb)

QA Review Completed. Moved to Stage Ready,
