### ISSUE TITLE
Add Schedule E to the *.fec file generate code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#485]
Add the Schedule E transactions to the generated *.fec file in the Django backend so that they are included in the WebUpload and WebPrint submissions.

**Tasks**

- Add the Schedule E definitions to the web_services app
- Add SchE.json file to the dot_fec/schema_fields directory

**QA Notes**
There is no way to enter Schedule E data yet from the front-end so only testing available are the API unit tests. Screenshots and links to successful unit tests are in the ticket comments below.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

QA Notes: Automated test results here: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2192/workflows/5088b6cc-26e1-455f-8c0f-1c1b6927ea92/jobs/6965
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/f3419c2d-82fc-4bf0-a9eb-7204ac8e6037)

**Comment by WiseQA** [comment]
QA review of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6d9efc3a-c432-49a4-9886-48434862c2cb)

QA Review Completed. Moved to Stage Ready,
