### ISSUE TITLE
Remove unused `posts` app

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#5]
The `posts` app is dead/demo code and should be removed:

https://github.com/fecgov/fecfile-online/tree/develop/django-backend/fecfiler/posts

It looks like there's also posts-related code in the /static/ directory.

**Acceptance Criteria:**
- [x] The django-backend/fecfiler/posts directory no longer exists in the repo
- [x] The django-backend/static/templates/posts directory no longer exists in the repo

**Comment by mjtravers** [comment]
Ready for QA. The file system to validate the directories exist are here:

- https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend/fecfiler
- https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend/static/templates

**Comment by mjtravers** [comment]
@WiseQA Here are links to the "before" state of the directories where the posts directories were removed:
- https://github.com/fecgov/fecfile-web-api/tree/sprint-2/django-backend/fecfiler
- https://github.com/fecgov/fecfile-web-api/tree/sprint-2/django-backend/static/templates

**Comment by WiseQA** [comment]
Verified before state and after state of django-bacckend/fecfiler posts directories were removed.  Verified django-backend/static/templates posts directories were removed.

QA review completed.  Moved to Stage Ready.
