### ISSUE TITLE
Upgrade Django to latest LTS version

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#501]
Latest LTS version of Django is 4.2.7, as of 11/14/2023

The automated safety dependency check is reporting vulnerabilities in our current version of Django

![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/ad35b381-9920-4a30-a59a-95f31c6f6d04)

Link to fail report: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2191/workflows/f5f57aaa-9b57-431a-9cf7-e1c7818ad4ce/jobs/6963

The task is to upgrade Django to v4.2.4 and then remove the exceptions listed in the .safety.dependency.ignore file

**QA Notes**
To pass QA, the API unit tests must pass.

**Comment by dheitzer** [comment]
vmware outage is currently causing our cloud.gov deployment to fail.  Waiting for this to resolve before moving this to CR.

**Comment by mjtravers** [comment]
Pass CR. Sending to QA.
Here is the unit test report:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2650/workflows/ae6d578d-e672-43bc-997e-f1c650340987/jobs/8381
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--437cb61715fde0e5464456fe6d125686848662ba/image.png)

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ptQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cbfd50e25e9f3a97deab5c08adcaa0252771aa9/image.png)

QA Review Completed.   Moved to Stage Ready.
