### ISSUE TITLE
Remove scha_transactions app from Django backend

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#502]
The scha_transactions app is not longer used after a big API refactoring a few months ago. It is causing additional and unnecessary make migration commands to be created whenever make migrations is run.

**DEV NOTES**
Remove references/dependencies in other Django apps  to the scha_transactions app
Remove the scha_transactions app

**QA NOTES**
Ticket passes if unit tests for API pass

**Comment by mjtravers** [comment]
**DEV NOTE:** End goal of this ticket is to remove the scha_transactions app from Django settings and from the file system. The additional database cleanup discussed will be listed in a future ticket.

**Comment by dheitzer** [comment]
unit tests https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2362/workflows/92e709d2-82bc-4756-98c8-02e4d78b1e15/jobs/7495

**Comment by dheitzer** [comment]
unit tests [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE1tQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83749fceacfb1b199cfb3b735d39423193a967a8/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUV6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e047de87ac87d5e0d8a65e735feabeaa15ed8fa/image.png)

QA Review Completed. Moved to Stage Ready,
