### ISSUE TITLE
Create Django model for Form 1M

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-api#509]
Create a Form 1M Django model. The f1m data needs to have its datbase table and REST API endpoints created in the Django app backend. The app setup will be similar to the same setup created for the f3x.

**Details**

- Validation and aggregation of model fields will be covered in a future ticket
- Database tablename will be f1m_summaries

**Acceptance Criteria**
- [] Basic CRUD operations from model to new database table: f1M_summaries
- [] Table has additional tracking columns: TBD 
- [] unit tests for basic CRUD operations
- [] Google-style code documentation
- [] info and debug logging
- [] Model property names must match f1M schema property names

**QA Notes**

**Comment by mjtravers** [comment]
Passes CR. Sending to QA
Unit tests: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2605/workflows/d3ffc89c-9051-46ae-a610-1901e1f339a5/jobs/8223
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4719062c25da4254326185ccdfbc6c1cb14c0c53/image.png)
