### ISSUE TITLE
Create Django model for Form 99

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-api#511]
Create a Form 99 Django model. The f99 data needs to have its datbase table and REST API endpoints created in the Django app backend. The app setup will be similar to the same setup created for the f3x.

**Details**

- Validation and aggregation of model fields will be covered in a future ticket
- Database tablename will be f99_summaries

**Acceptance Criteria**
- [x] Basic CRUD operations from model to new database table: f99_summaries
- [x] Table has additional tracking columns: TBD 
- [x] unit tests for basic CRUD operations
- [x] Google-style code documentation
- [x] info and debug logging
- [x] Model property names must match f99 schema property names

**QA Notes**

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**QA Notes: Link to tests:** https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2435/workflows/a9f91902-1c82-459e-95f7-017831d6c9fe/jobs/7694
