### ISSUE TITLE
Add Form 1M to the *.fec file generate code

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-api#512]
Add the Form 1M transactions to the generated *.fec file in the Django backend so that they are included in the WebUpload and WebPrint submissions.

**Tasks**

- Add the Form 1M definitions to the web_services app
- Add f1M.json file to the dot_fec/schema_fields directory

**QA Notes**
There is no way to enter Form 1M data yet from the front-end so only testing available are the API unit tests. Screenshots and links to successful unit tests are in the ticket comments below.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA
Unit tests: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2605/workflows/d3ffc89c-9051-46ae-a610-1901e1f339a5/jobs/8223
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4719062c25da4254326185ccdfbc6c1cb14c0c53/image.png)

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8d9157110af1adcd7cae04322011311e0441ad5/image.png)

QA Review Completed. Moved to Stage Ready,
