### ISSUE TITLE
Add Form 99 to the *.fec file generate code

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-api#514]
Add the Form 99 transactions to the generated *.fec file in the Django backend so that they are included in the WebUpload and WebPrint submissions.

**Tasks**

- Add the Form 99 definitions to the web_services app
- Add f99.json file to the dot_fec/schema_fields directory

**QA Notes**
There is no way to enter Form 99 data yet from the front-end so only testing available are the API unit tests.

**Comment by mjtravers** [comment]
For QA, unit test link: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2411/workflows/2e27d40b-5ec8-4b63-a0a7-37015ed5b0a3/jobs/7633

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmMxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--933c3c937dfabfe3e44a98b6c28163101fa08219/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGREQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dccdbbbf8b4440e2bb90a64fa9fa86c854a34c7/image.png)

QA Review Completed. Moved to Stage Ready,
