### ISSUE TITLE
System to differentiate between parent/child transactions and associated transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#526]
Task: Use system to relate repayments to debts/loans that is different from the one relating parents and children. Both use the Back Reference ID field.

### Acceptance Criteria
- Debt/Loan repayments will not inherit the itemization of the Debt/Loan (which they would if it was a parent/child relation)
- Debt/Loan repayments will be deleted the same way children are deleted, when the Debt/Loan is deleted
- Back reference ID of debt or loan repayments will match back reference ID of the respective debt or loan they are associated with.

### QA Notes
The relation of repayment to loan seen in the table here should be reflected in the .fec
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0d5f9c2fe79316bf63dc9b0ca8b5e08148286f2/image.png)
See below how the loan repayment references the loan on the line after it
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1FQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--433585837fc432ed5a73d9c58e43d875d795c3cc/image.png)

### DEV Notes
- Debt has already been implemented in app#1168
- Create new foreign key to transaction table for repayments to their Debt/Loan. (make delete cascade)
- Set Debt/Loan FK when creating a repayment
- Set backreference ID in .fec composer when Debt/Loan FK points to Debt or Loan for repayments (no backreference id in debts and loans)
- We will have 2 new foreign keys on the transaction: debt_id and loan_id

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@toddlees add screenshots for QA review please - thanks !

**Comment by WiseQA** [comment]
During QA and DEV review there is an issue with old loan repayments.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--194ad155534a92b55042386083dd898a0df83b78/image.png)

@mjtravers @toddlees moving back to In-Progress for fix and screenshot updates once fix is implemented.

**Comment by WiseQA** [comment]
QA review verified the transaction ID and associated with transactions relation of repayment to loan seen in the table are shown in the .fec

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9904c46b60fd1b4be672c4020d88a52771b83757/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1lGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--936883957691571eed4f163bd85996b5ec46757d/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a04cb0515f9bc4292db946cd80d82ef74f431f6e/image.png)

QA Review Completed.   Moved to Stage Ready.
