### ISSUE TITLE
Add validation rules to contacts Django model for all 4 contact types

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#54]
Integrate the validate python package into the Django contacts app to validate inserts and updates.

**Acceptance Criteria**
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. validation fails return output of validation python package

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/23/22:** This is server-side validation, not client-side.

**Comment by WiseQA** [comment]
Verified unit test passed successfully as denoted above:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/81382125-d46c-45be-8d8b-60f2d00a394f)

QA review completed.  Moved to Stage Ready.
