### ISSUE TITLE
Update dot fec composer to handle F24, F99, F1M

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#558]
After we are able to save F24, F99, F1M into the app database, the code that outputs the dot fec file [ dot_fec_composer.compose_dot_fec() ] needs to be generalized from just working with the F3X spec.

In addition, for the F99, the compose code will need to be updated to handle the large, free-form text field.

**DEV Tasks:**

1. Remove F3X references from compose_dot_fec()
2. Add generalized handling of current forms: F3X, F24, F99, and F1M
3. Implement handling of additional characters of the F99 comments field with regard to carriage returns and new lines

**QA Notes**
There are not F24, F99, and F1M reports in the system yet so QA will be visual inspection that unit tests pass for backend.

**Comment by AureliaKhorsand** [comment]
[F99 example 1](https://docquery.fec.gov/csv/890/1730890.csv)
[F99 example 2](https://docquery.fec.gov/csv/306/1730306.csv)

**Comment by AureliaKhorsand** [comment]
@mjtravers would this also apply to Form 1M? what about future forms?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @toddlees please add unit test link as we have in previous tickets for QA review - thanks

**Comment by mjtravers** [comment]
Here is the unit test link and screen shot:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2673/workflows/2749d735-226d-4fea-889d-1048c3c6bbef/jobs/8451

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01MQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdc73ad9ec295d60dab121d80f798f2297dc6904/image.png)

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c5299ba4aa7b22e64ba66006d51d62bbb675fa0/image.png)

QA Review Completed. Moved to Stage Ready.
