### ISSUE TITLE
Update stage/prod redis service to appropriate (prod) tier

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#582]
### Business Reason ### 

Technical requirement: current `redis-dev` is for non-production use. We should upgrade to a production-tier service before getting test users on the system. Info: https://cloud.gov/docs/services/aws-elasticache/

We have [10 nodes included](https://cloud.gov/pricing/#additional-charges), so we can run `redis-3node` (3 dodes) in dev, stage, and prod. If we want to spin up a load test environment, we could consider running `redis-dev` (1 node) in dev and `redis-3node` (3 dodes) in test, stage, and prod

Document how the upgrade process works in regard to preserving (or not) the in-flight data currently in redis during the upgrade.

**Comment by dheitzer** [comment]
This upgrade seems pretty straight forward.  The UI allows us to edit the instance type and there is also a CLI option for this using `cf update-service` https://docs.cloudfoundry.org/devguide/services/managing-services.html#update_service

I was not able to find CF documentation that definitively states that in-flight messages are preserved during an update_service command, however [this ElastiCache documentation](https://aws.amazon.com/blogs/aws/elasticache-for-redis-update-upgrade-engines-and-scale-up/) indicates that it will as well as [this SO answer](https://stackoverflow.com/a/72056687/6501190).

**Comment by toddlees** [comment]
@dheitzer @mjtravers  @lbeaufort Recommend adding `--s3` flag to your run-task command so that it reads the file in s3 rather than the one in the django source:
`cf run-task fecfile-web-api --command "python ./django-backend/manage.py load_committee_data --s3" --name run-load-committee-data`

**Comment by dheitzer** [comment]
> @dheitzer @mjtravers @lbeaufort Recommend adding `--s3` flag to your run-task command so that it reads the file in s3 rather than the one in the django source: `cf run-task fecfile-web-api --command "python ./django-backend/manage.py load_committee_data --s3" --name run-load-committee-data`

right, good catch! tested and updated.

**Comment by toddlees** [comment]
@MitchellTCG this is an ongoing ticket as we apply it to stage and production. What bucket do want it in while we wait to apply it to stage?

**Comment by mjtravers** [comment]
@MitchellTCG @WiseQA This ticket is ready for QA on DEV but we need to keep it in QA and on hold until we deploy to STAGE and PROD when we cut the release. I am marking it On Hold so we remember to do the Redis upgrade when we deploy the release branch to STAGE.

QA Notes: To test, a user should be able to generate a Print Preview. If Redis is broken, then we won't be able to create *.fec files, print preview, or submit reports to EFO.

**Comment by WiseQA** [comment]
QA review tested per DEV notes above.  A user should be able to generate a Print Preview. If Redis is broken, then we won't be able to create *.fec files, print preview, or submit reports to EFO.

QA Review Completed.   Moved to Stage Ready.

**Comment by lbeaufort** [comment]
Deleted `fecfile-api-redis_mved` in `stage` and `prod` spaces after confirming with @dheitzer
