### ISSUE TITLE
Upgrade postgres version to 14, extend backup retention period to 35 days

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#583]
### Business Reason ### 

- Upgrade postgres version to 14
- extend backup retention period to 35 days 

Technical requirement: The QASP specifies we need to be no more than one major version behind on major underlying technology. We're currently running postgres version 12, which reaches EOL in one year. The newest version is 16, and cloud.gov supports versions 15 and below. Starting with version 15, connections must be over SSL so if this isn't feasible I think version 14 is fine for now.

While we're at it, we should extend the backup retention period to 35 days (see cloud.gov docs - default is 14 days)

https://cloud.gov/docs/services/relational-database/ 

### Acceptance Criteria ### 

**If** [precedent]
**When** [action]
**Then** [result]

### Technical notes ### 

- Circle config
- Docker image
- Cloud.gov service instances: https://github.com/fecgov/fec-cms/wiki/Backup-or-Restore-Wagtail-PostgreSQL-database-in-dev,-stage,-or-production
- AWS description of using SSL with PostgresSQL DB instance: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html#PostgreSQL.Concepts.General.SSL.Requiring
-

**Comment by mjtravers** [comment]
@lbeaufort Let's plan on upgrading to version 15 and then fall back to 14 is the SSL setup becomes a blocker.

**Comment by mjtravers** [comment]
The work for this ticket has been moved to this ticket: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/592

Closing ticket.
