### ISSUE TITLE
DevOps tasks for STAGE and PROD

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#587]
Now that we have test users coming on board, there are a few tasks needed to prepare STAGE and PROD:

**STAGE & PROD**

- [x] 1. Django: Replace error messages sent from Django back-end with 500 response
- [x] 2. Angular: compile in prod mode with code minimization and no debugging setup
- [x] 3. CircleCI: Run e2e tests on commits to release/sprint-# and main branches
- [x] 4. Turn on the EFO connection & MAKE IT STICK

**JUST PROD**

- [x] 1. Update PROD setting in Cloud.gov environment variables to point to Test EFO services. (variable FEC_API)
- [x] 2. Add Login.gov sanbox app for PROD and adjust environment variable with Login.gov APP ID
- [x] 3. Add PROD login account for Shelly

**DEV NOTES**
Add a screen shot of the new pop up error message for QA to verify.

**QA NOTES**
To pass: a user must be able to successfully log into STAGE and PROD using Login.gov and see their committee account information.

**Comment by toddlees** [comment]
It appears that our setting for turning on the EFO connection is getting reset somehow.  We need to figure out what is reseting it and how to make it stick

**Comment by dheitzer** [comment]
reached out to QA to login to prod so we can assign the committee id per QA notes.

**Comment by dheitzer** [comment]
New popup err message [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1liQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfa745dfe6cf82545e55645537429989ea20132d/image.png)

**Comment by mjtravers** [comment]
I am able to log into PROD now, but am getting a 500 error when trying to create a report:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32f201fe004c9c5ada2b7e194684a020baebf264/image.png)


Also, I'd like this ticket to include making sure all the cloud.gov spaces have the same ENV vars and same vars in the the credential services. Currently, the dev space has 18 variables in the dev api application, 14 variables in the stage api application, and 15 variables in the prod api application. We want all 3 spaces to be the exact same whenever possible. It looks like the credentials services for all 3 spaces have the current keys stored: DJANGO_SECRET_KEY, OIDC_RP_CLEINT_ID, FEC_FILING_API_KEY, and FEC_API_KEY. The prod space still has the DJANGO_SECRET_KEY declared in the app api, so it should be removed. It'd be preferable to have the OIDC_RP_CLIENT_SECRET in the credentials service as well, but seeing that there is some formatting to be done just to get it into the app env variables, we'll move that task into a separate ticket because it may be tricky to get the key into the credentials service.

Also, all three cloud.gov spaces have the env variable DJANGO_SETTINGS_MODULE set to "fecfiler.settings.production". Let's verify that this is correct and what we want across all 3 cloud.gov spaces.

Sending ticket back to In Progress.

**Comment by mjtravers** [comment]
All 3 spaces have had their env variables organized and is documented here: https://docs.google.com/spreadsheets/d/1tTr2-TmIX2izjjnjQnhXW63--HWdMVkTYLPvqut0XAA

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Unit tests:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4567/workflows/f21ff160-25e9-470b-9bf6-ff75d4257ca2/jobs/16299
<img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b42cc4773372f480a2286735d7fc0ba53c2b9638/image.png" alt="image.png" />
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2829/workflows/d845e34b-b71f-4069-94c0-bfa4337fcc64/jobs/8932
<img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dc7e636dcf5b5c2246a1872ae57646f23e34125/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
On-hold with ticket #1339 until EFO connection is fixed.

**Comment by mjtravers** [comment]
I have noticed that the order of operations may not be correct for blocking deployment on an e2e test fail. Moving back to In Progress to double-check.

**Comment by mjtravers** [comment]
Deployment issue resolved and code passes CR. Sending back to QA. See above comments for test screenshots.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.   Per QA notes from DEV - To pass: a user must be able to successfully log into STAGE and PROD using Login.gov and see their committee account information.

<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVN1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be1da3c20422dbc22121aa816152db97bb6bb6ad/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
