### ISSUE TITLE
Update Django OIDC library with upstream changes and add unit tests run in CircleCI

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#601]
### Business Reason ### 

Technical requirement: We're using a [forked copy of the mozilla-django-oidc package](https://github.com/fecgov/fecfile-web-api/blob/0e94d46f90f79dbcebbd86c841e6434378e047d9/requirements.txt#L27). There have been some fixes since we forked a copy - we should incorporate upstream changes into our forked copy.

Ensure all unit tests pass and add meaningful test coverage before upgrading upstream changes.

Also, in the forked OIDC package perform the following code cleanup tasks:

- [X] Final test deploy: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3145/workflows/83760e59-7a96-49c5-8f02-f515af43a595/jobs/9724
- [x] Add test coverage to our fork modifications
- [x] Review/address TODO's/tech debt and break out large tasks if outside point scope of this ticket
- [x] Remove sensitive data from debug statements
- [X] Review exceptions in logs
- [X] Clean up comments
- [x] Use `black` to unify single/double quotes and formatting across project
- [x] consider hooking up SonarCloud
- [X] Review logging statements to make sure they're helpful
- [x] Ensure clean linting report
- [x] Consider hooking this library up to Circle so the tests can run
- [x] Pinning sub-dependency versions
- [x] Update our fork with latest changes in OIDC repo
- [X] Add test coverage report
- [x] Run snyk on dependencies
- [ ] ~Consider running suggested test apps locally: https://github.com/mozilla/mozilla-django-oidc?tab=readme-ov-file#local-development~ spike ticket: https://github.com/fecgov/fecfile-web-api/issues/739
- [ ] ~Consider setting up integration tests/local dev on web api with test provider app (can't currently test with login.gov and local)~ spike ticket: https://github.com/fecgov/fecfile-web-api/issues/739

### DEV Notes ###
https://github.com/mozilla/mozilla-django-oidc/issues/502

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

QA Notes: Ticket passes if user can login and logout of FECFile Online using Login.gov

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Ticket passes if user can login and logout of FECFile Online using Login.gov built for this ticket per DEV.

QA Review Completed.   Moved to Stage Ready.
