### ISSUE TITLE
Add committee accounts to api for UAT users

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#604]
New UAT users are being added to the STAGE server for testing purposes. They need new committee accounts set up in the STAGE code branch. This branch will eventually be merged into the develop branch.

Add UAT users to STAGE branch for access to FECFile Online.

**QA NOTES**
Verbal confirmation that the new accounts work will be given by UAT users themselves and recorded in this ticket's comments.

#### Before 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlQ4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc7010c584e06798b64c9b807a71d4f21dc2bbcb/unnamed-1.png)

#### After
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmI4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22909f67340fae3caf2203bcd0217f171f70619c/0.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Further comments will be added when new users are able to log into STAGE.

**Comment by WiseQA** [comment]
No QA review needed on this ticket.  DEV working with new users and STAGE log in.

Moving to Stage Ready.

**Comment by WiseQA** [comment]
Per @MitchellTCG moving ticket back to in-progress as additional information is needed.

**Comment by dheitzer** [comment]
Added Shelly's committee id (C00100495) to FEC_API_COMMITTEE_LOOKUP_IDS_OVERRIDE environment variable on DEV and STAGE to allow here to see the overridden account info for this id.

**Comment by WiseQA** [comment]
No QA review needed on this ticket.   Moved to Stage Ready.
