### ISSUE TITLE
Increase celery-worker app to 2 instances, separate manifest files

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#612]
### Business Reason ### 

Technical need: Increase celery-worker app to 2 instances for production-readiness on at least prod and stage spaces - might consider including dev to keep them the same. 

Create manifest files for dev/stage/prod so we can have more control over the environments

As a committee administrator, I will be able to reliably file my reports so that I can meet my compliance requirements

### Acceptance Criteria ### 

**If** [precedent]
**When** [action]
**Then** [result]

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
For QA. All unit tests pass and new configuration deployed to DEV without any issues:

https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2828/workflows/239aadaf-8e60-481d-93cb-980625842567/jobs/8928
<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ea14835e0bf71f5cc5df8d7c76cd2bc69d3a711/image.png" alt="image.png" />

Web Services is running with 2 instances:
<img width="546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb90b33218d92db1869ddc5d7a8b605c9d85d019/image.png" alt="image.png" />
