### ISSUE TITLE
CircleCI: Migrate from deploy to run in all config files

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#634]
We received this notice from CircleCI that we need to update the name of a step in our CircleCI files:

https://circleci.com/docs/migrate-from-deploy-to-run/

- [x] Update config.yml in app repo
- [x] Update config.yml in api repo
- [x] Test deploy to ensure still works

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
This is a DevOps ticket to be verified by successful deployment and unit tests.
Deployment was successful to DEV.

Unit tests for app code:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/b2743630-f3dc-4991-bbf0-4b0e1c122ac4)


Unit tests for api code:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/60d54455-2998-45ec-9515-27cdff7ceff6)

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

Moved to Stage Ready.
