### ISSUE TITLE
Research: Investigate integrating PostgreSQL performance logging into Kibana

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#642]
AS a system administrator, I want to be able to see graphical Kibana charts on database performance and system monitoring. Metrics such as open connections and long running queries.

**Notes from 12/15/2023 discussion:**

_Query to look at connections:_
```sql
select 
    A.total_connections, 
    A.non_idle_connections, 
    B.max_connections,
    round((100 * A.total_connections::numeric / B.max_connections::numeric), 2) connections_utilization_pctg
from
  (select count(1) as total_connections, sum(case when state!='idle' then 1 else 0 end) as non_idle_connections from pg_stat_activity) A,
  (select setting as max_connections from pg_settings where name='max_connections') B;
```
_Available postgres statistics_
https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW

_Example query to view stat activity_
select pid, usename, query_start, query from pg_stat_activity;

_Possible Django plugin to view statistics_
https://github.com/Opus10/django-pgactivity

Based on findings of this ticket, a follow up ticket will be created to implement the solution worked out.

- [x] Reach out to cloud.gov to see if they have suggestions

**Comment by lbeaufort** [comment]
Emailed cloud.gov today

> Hi team,
>  
> We’re using cloud.gov’s postgres RDS service for a Django app that’s in development and are beginning to think about database observability. It’s my understanding that the only way to get database stats like number of database connections, etc is to ssh into the database or pipe data to the application logs so we can view them in Kibana.
>  
> I just wanted to check with you all to see if I’m missing anything – do you have any recommendations for database observability for RDS services?
>  
> Thanks in advance!
> Laura
>  
> In case you’re interested –
> ticket: https://github.com/fecgov/fecfile-web-api/issues/642
> WIP PR:  https://github.com/fecgov/fecfile-web-api/pull/645

**Comment by lbeaufort** [comment]
>  Hello Laura,
> 
> Thank you for your ticket and questions. Currently, there is not a way to provide this information outside of a periodic support request for us to provide you with a snapshot of your requested database metrics.
>  
> You are correct, as you mentioned, for now, you can SSH into the database, at which point most or all of the statistics tables provided by Postgres should be available as mentioned in the documentation which you also linked in your Github Issue : [https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW]
>  
> The binding credentials provided with the service should have sufficient permissions to read these tables, so you could view statistics ad hoc easily. Additionally, you could potentially run a tool as a CF app bound to the RDS instance and use that to look at database statistics and interact with your Postgres database such as the tool you mentioned in the Github issue as well: [https://github.com/Opus10/django-pgactivity]
>  
> I apologize we could not offer any further solutions regarding this matter at this time. We are aware of our customer's interest in better database observability tooling and we are exploring possible solutions. Please let us know if you have any other questions.

**Comment by lbeaufort** [comment]
Side note: Using a monitoring tool, while more dev friendly, would have security implications beyond those of printing stats to the logs.

**Comment by mjtravers** [comment]
Ticket was reviewed in the weekly dev meeting and passes "CR" for the research and suggested implementation. Sending ticket to Stage Ready.

**Comment by cnlucas** [comment]
More details from cloud.gov that might be helpful for you all: 
```
High level RDS metrics like CPU, DB connections, free space, memory, disk queue etc. are stored for 2 months. 
 
The performance insights data are only retained for 7 days. These are the highly granular data on SQL queries and their performance. If you want to look into those data, we should probably schedule a weekly pairing session to look into them. 
 
```

We had to opt into performance insights which required a DB restart.
