### ISSUE TITLE
Disable Django REST login page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#643]
### Business Reason ### 

I think we should disable this page: https://fecfile-web-api-dev.app.cloud.gov/api-auth/login/

I found it by going to https://fecfile-web-api-dev.app.cloud.gov/celery-test/ and hitting "log in"

https://github.com/fecgov/fecfile-web-api/blob/fc7d877317b6e6e16c978bf5a88bfeba96d64809/django-backend/fecfiler/urls.py#L19

As a [role], I will be able to [blank] so that I can [business reason]

### DEV NOTES ###
The /api-auth path is defined in the fecfiler/urls.py file.

### Acceptance Criteria ### 
The following link does not show a login page: https://fecfile-web-api-dev.app.cloud.gov/api-auth/login/

**Comment by mjtravers** [comment]
Passes CR. QA: See acceptance criteria in bottom of ticket description for link to the page that should no longer have a login screen visible.
The screenshot below should NOT be visible at the link:
<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d962ee1ed729eabcdb69ba661d2e8dd20f42be1f/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection link to the page that should no longer have a login screen visible. built for this ticket per DEV.

The screenshot below should NOT be visible at the link:

<img width="352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9EQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f82b26efa6bb013bf2cfe15ca9b88758016fb8b/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
