### ISSUE TITLE
Web services follow-up: get creds from credential service rather than application environment

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#644]
Business Reason 

Follow-up from and blocked by api#641: [https://github.com/fecgov/fecfile-web-api/pull/641#pullrequestreview-1798478230](https://github.com/fecgov/fecfile-web-api/pull/641#pullrequestreview-1798478230)

The web service needs the `FEC_FILING_API_KEY` and we're currently storing it in both the web service app variables and the creds service. We should get creds from service rather than application environment.

As a committee administrator, I will be able to reliably file my reports so that I can meet my compliance requirements

*   [x] Update cloud.gov web-services application variables
*   [x] Update env variables documentation spreadsheet: [https://docs.google.com/spreadsheets/d/1tTr2-TmIX2izjjnjQnhXW63--HWdMVkTYLPvqut0XAA/edit#gid=0](https://docs.google.com/spreadsheets/d/1tTr2-TmIX2izjjnjQnhXW63--HWdMVkTYLPvqut0XAA/edit#gid=0)

### QA Notes ###
 
  
 null

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

**Comment by mjtravers** [comment]
There is no code to review as the changes were made in the Cloud.gov UI. I verified that the FECFILE_API_KEY is no longer in the environment variables but in the credentials service for DEV, STAGE, and PROD.

For QA: Here is a screenshot showing the FECFILE_API_KEY variable in the credentials service. All sensitive information in the screenshot was redacted.:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/ca710d9e-c27c-4460-a876-9e9c7f2d9510)

**Comment by WiseQA** [comment]
Per DEV no code review.  QA visual inspection on DEV screenshot (see above) showing the FECFILE_API_KEY variable in the credentials service. All sensitive information in the screenshot was redacted

Moved to Stage Ready.
