### ISSUE TITLE
Change logging output from Django app to STDOUT

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#648]
The default logging for Django log handlers is to the STDERR output. This is causing the output to be marked as an ERR by the cloud.gov log viewer.

The task is to update the log handlers in the Django settings to send all non-error logging levels to STDOUT.

See:
https://stackoverflow.com/questions/24117481/django-loggers-correct-output-to-stdout-and-stderr
https://docs.djangoproject.com/en/4.2/topics/logging/

### Acceptance Criteria ###
Screenshot of cloud.gov log output with Signal info messages marked as info and not a red ERR record.

2024-01-03T10:40:13.08-0500 [APP/PROC/WEB/1] **ERR** 2024-01-03 10:40:13,083 [INFO] fecfiler.reports.signals: F3XN Report: c22cd466-3031-40a8-be0e-717f7a6de938 was updated

**Comment by lbeaufort** [comment]
@mjtravers I believe I addressed this here:  https://github.com/fecgov/fecfile-web-api/pull/672/files#diff-cb8980399df859489945004e518241f2ba4c598b0f5c2e047ba2c167d9e8b4cbR254

```json
"handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "plain_console",
                "stream": sys.stdout,
            },
            "cloud": {
                "class": "logging.StreamHandler",
                "formatter": "key_value",
                "stream": sys.stdout,
            },
```

**Comment by mjtravers** [comment]
Ticket is OBE. Closing.
