### ISSUE TITLE
Set up Pingdom to ping celery and database

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#649]
There is a risk that the celery workers can fail silently. Pingdom will be set up to periodically hit a /celery-test/ endpoint that will indicate if the celery service is up and running.

Additionally, Pingdom alert should be set up to hit an endpoint that, after running a test query against the database, report back whether the database connection and query were successful or not.

DEV NOTES

There is already an enpoint set up as "/celery-test" that is set up in the fecfiler/urls.py file. The function for this test can be updated if necessary to adapt to whatever Pingdom needs to see to verify the service is up.

To let the user know that the db is up without letting them fire off a db task without logging in, we should monitor the state of the database on the api, store that state and return it on the ping endpoint

Acceptance Criteria

A message is automatically sent from Pingdom to the Slack #fecfile-alerts channel when the Celery web-service is not responding for DEV, STAGE, or PROD

### QA Notes ###
To verify, you can look at 2 URLs in the browser and see if a valid response comes back:

[https://dev-api.fecfile.fec.gov/devops/celery-status/|https://dev-api.fecfile.fec.gov/devops/celery-status/]

should display

!image-20240827-174144.png|width=326,height=66,alt="image-20240827-174144.png"!

[https://dev-api.fecfile.fec.gov/devops/database-status/|https://dev-api.fecfile.fec.gov/devops/celery-status/]

should display

!image-20240827-174236.png|width=326,height=66,alt="image-20240827-174236.png"!

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

 See full ticket and images here: [FECFILE-243](https://fecgov.atlassian.net/browse/FECFILE-243)

**Comment by lbeaufort** [comment]
I'd like to consider changing the Pingdom alerts for the API to also run queries rather than hitting the status page. It seems beneficial to have a test query endpoint like the one for celery.

**Comment by mjtravers** [comment]
> @mjtravers I'd also like to consider changing the Pingdom alerts for the API to also run queries rather than hitting the status page. It seems beneficial to have a generic test query endpoint like the one for celery. If you agree, we could add it to this ticket or create a separate one.

Yes, that sounds good to me. What kind of query? Are we talking about a custom api endpoint that returns just some python generated response or a query to the database, too?

**Comment by mjtravers** [comment]
@lbeaufort Added a database query check for pingdom in this ticket and increased the points accordingly.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG why is this on hold? Can we add that to a comment in this ticket?
