### ISSUE TITLE
Remove unused phase 1 fixtures and scripts

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#650]
There are a number of fixture data files and scripts in the code base that are no longer needed.

For each file listed below, verify the file is no longer in use and then remove from the code base:

- [x] django-backend/fixtures/base_data_tmp.json
- [x] django-backend/fixtures/base_data.json
- [x] django-backend/fixtures/committee_base_data.json
- [x] django-backend/fixtures/committee_updated.json
- [x] django-backend/fixtures/forms_committee.csv
- [x] django-backend/scripts/create_new_user.sql
- [x] django-backend/scripts/generate_transaction_record_fixture.py
- [x] django-backend/scripts/postinstall.sh
- [x] django-backend/data.json

### Acceptance Criteria ###
A review of the GitHub repo shows that the files are not longer present:
https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend
https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend/fixtures
https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend/scripts

**Comment by mjtravers** [comment]
Passes CR. QA see links at bottom of ticket description to see directories where files have been removed.
Sending to QA.

**Comment by WiseQA** [comment]
QA review visual inspection per DEV links at bottom of directories where files have been removed.

A review of the GitHub repo shows that the files are not longer present:
https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend
https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend/fixtures
https://github.com/fecgov/fecfile-web-api/tree/develop/django-backend/scripts

QA Review Completed.  Moved to Stage Ready.
