### ISSUE TITLE
Convert api logging output to JSON, add better log data

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#651]
The application logs in cloud.gov (Kibana) are searchable if in JSON format.

In addition, we will add the user and committee information to the JSON output so that we can specify those field in log search queries.

Cloud.gov documentation: https://cloud.gov/docs/deployment/logs/
Here is the python JSON log formatter recommended by cloud.gov: https://github.com/madzak/python-json-logger 
(and an issue that addresses Django integration: https://github.com/madzak/python-json-logger/issues/51 and exceptions: https://github.com/madzak/python-json-logger/issues/138)

- [ ] Convert the Django logging format to JSON
- [ ] ~Add user email to all output log statements~ @mjtravers I don't think we should print PII to the logs
- [ ] Add user id GUID to all output log statements
- [ ] Add FEC committee id to all output log statements

### Acceptance Criteria ###
- [ ] Screenshot of the cloud.gov api log showing JSON formatting.
- [ ] Screenshot of Kibana search using committee id: https://logs.fr.cloud.gov/goto/c8d136245053a3ba9122b342b9d658e9

**Comment by lbeaufort** [comment]
Moved to sprint 37 per @MitchellTCG

**Comment by lbeaufort** [comment]
After discussing with the cloud.gov team, there are some fundamental issues with json logging on cloud.gov that can make some logs not appear in Kibana. They're testing alternatives, but in the meantime I think a key-value pair in cloud.gov would add some benefit. We could consider picking up json logs once this issue is addressed: https://github.com/cloud-gov/logsearch-boshrelease/issues/161

**Comment by lbeaufort** [comment]
Questions for cloud.gov that would influence future work on trying to get json to work (after they address their issues)
- [ ] Any plans for adding Database observability for RDS?
- [ ] When Json works reliably, can we build dashboards off those custom fields? aka have them as output fields/columns in the log rows?

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

Unit test results: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3047/workflows/f4bc7cad-bc6f-48c9-bb1f-08507190ffc5/jobs/9484

Screenshot of unit tests passing:
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm9uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97bcac93ae21e76547b583af86b467e30d5ca3c3/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1VuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fc3c47788171f142ff6de2b33125cb8269b65af/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
