### ISSUE TITLE
PERFORMANCE - Implement transaction performance refactoring

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#656]
Transactions performance issues noticed during testing for Loans and Debts.

This ticket is to implement in the code the findings and resolution strategies outlined in the spike research ticket [#633](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/633)

### QA Notes ###
See [#633](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/633) for screenshots of issue.

**Comment by toddlees** [comment]
Unit tests passing:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3350/workflows/aafe2a84-6fcb-4074-8e10-7fa0166109d2/jobs/10238
<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01FQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--466e7e86bc4431150dfc0aa4a16179daffc8ebd6/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Passes CR. Ready for QA. There are no front end features to test. See comment above for successful run of unit testes.

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

Moved to Stage Ready.
