### ISSUE TITLE
Improve migrations process for testing and deployment

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#67]
Creating this ticket per @mjtravers 

There are several changes that need to be made to keep the application in sync with the database.

- Some migrations are missing and need to be created with `./manage.py makemigrations` and commtted to the codebase
- Tests should fail when we forget to check in breaking migrations. When CircleCI  runs `makemigrations` for us this will be missed. One of the risks of not checking in these missing initial migrations is that there could eventually be a fairly complex migration conflicts.
- In addition, the `bin/run.sh` command for deployment to cloud.gov shouldn't make migrations. The source of the migrations should be the codebase.

Going forward, migration files should be generated by the developers and checked in with changes. The best way to do may be for the developer to complete code changes, log into the docker image (`docker exec -it fecfile-api /bin/bash`), run `./manage.py makemigrations`, and commit the migration(s) along with code changes.

**QA**
To verify that the CircleCI configuration script was updated and the new makemigrations files were created, view the [changed files here](https://github.com/fecgov/fecfile-web-api/pull/63/files)

**Comment by WiseQA** [comment]
Verified that the CircleCI configuration script was updated and the new makemigrations files were created:  (Note could not snip whole migration files use link above in QA to view whole file).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/de5ac5a8-77a5-4d3d-bca4-c3dc853bda7a)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7dade3d3-8ac5-4cf3-bac1-60097973e11c)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b0a92782-c6a8-4b88-b2c2-b1afc8bd4289)

QA review completed.  Moved to Stage Ready.
