### ISSUE TITLE
Build Kibana dashboard that displays API query times

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#677]
In order to have a way to view api performance, build a Kibana dashboard that displays the api query times.

The dashboard should allow for the identification of the top 3 slowest queries for a given set of log entries.

**Comment by lbeaufort** [comment]
Potential dasboard: https://logs.fr.cloud.gov/app/dashboards#/view/68ce0420-c1d9-11ee-ae62-a9916ae7bdbd?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1h%2Cto%3Anow))

**Comment by mjtravers** [comment]
For QA: Screenshot of new Kibana dashboard built for this ticket
<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDg1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d65cf38fb960b2489271a1ea639692180cbd24b1/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Kibana dashboard built for this ticket per DEV.

<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--605650ef7980fadb196582dc8e5c3cb141ad7706/image.png" alt="image.png" />

QA Review Completed. Moved to Stage Ready.
