### ISSUE TITLE
Create script to dynamically generate Locust test data

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#678]
This ticket is to generate a suite of report and transaction records that can then by used by Locust to populate the target test server.

See this PR as to how Locust needs the data formatted: https://github.com/fecgov/fecfile-web-api/pull/711/files

As a first start to prove the viability of the Locust strategy, create the following 3 test cases from the script:

- [x] generate F3X reports for a test committee
- [x] generate Individual receipt
- [x] ~~generate Joint Fundraising Transfer with child memos~~ For the same effect, Individual Receipts were linked in parent-child relationships to mock the retrieval of triple-transactions

**Comment by Elaine-Krauss-TCG** [comment]
An example of Locust testing running:
![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/8e1004bf-5ff5-4842-9f62-d20bfc5d64ca)

A screenshot of the data-generation script being run:
![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/34519252-5d69-4b41-ae89-cac24f1f4ce1)

A screenshot of one of the created .json files:
![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/768dbf7c-946f-4231-9f69-168399fd2fe3)

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

Moved to Stage Ready.
