### ISSUE TITLE
Switch to using `DEMO_KEY` FEC API key for local development 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#68]
Adding a ticket per @mjtravers 

The environment variable `FECFILE_FEC_WEBSITE_API_KEY` is required for tests to pass (this isn't great, I put in #64) so we should update the Dockerfile and CircleCI docs to use the `DEMO_KEY` API key (this is a working key) as the default for local development.

**QA**
The addition of the 'DEMO_KEY' value to the environment variable can be confirmed in [this config file](https://github.com/fecgov/fecfile-web-api/blob/develop/docker-compose.yml#L42)

**Comment by WiseQA** [comment]
Verified 'DEMO_KEY' value to the environment variable was updated:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ac9a9177-96ed-42f8-93ae-1b0e31d9ac63)

QA review completed.  Moved to Stage Ready.
