### ISSUE TITLE
Upgrade Sphinx to get api docs-build running again

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#682]
Our automated documentation builder is failing due to an old version of Sphinx.

Task is to upgrade it so CircleCI can run the docs-build step in the api repo.

<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd254QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--181d069e7a0e636b127bd8d3074ed28348bc4cfb/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
For QA: Here is a screenshot of Sphinx successfully running after the version fix:
<img width="723" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6e7cd818836d657c1a585a60d84653004ae2717/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Screenshot of cSphinx successfully running after the version fix: built for this ticket per DEV.

<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3FEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--237d3a4a9fa4ea0263639e5f93c8973e267b09a9/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
