### ISSUE TITLE
Keep django logs going to STDOUT but block from going to front end.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#689]
Currently, although not displayed in the front end, error messages are being sent out the API endpoints. The error messages should still go out to the STDOUT logging but not be sent out the API endpoint.

NOTE: System error messages should not go to the front-end but validation errors should.

When a validation error occurs in the api, a ValidationError object is handled in the fecfiler.utils.custom_exception_handler.

The ValidationError has the form:

ValidationError({'memo_text': {'report_id': [ErrorDetail(string='This field is required.', code='required')]}})

**While keeping all exception errors to STDOUT, only allow validation errors to be sent to the front-end, other exceptions are blocked and a 500 error sent. To be clear, Validation exceeptions go to both front-end and STDOUT.**

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by MitchellTCG** [comment]
@toddlees can you capture a video of this working?

**Comment by toddlees** [comment]
https://github.com/fecgov/fecfile-web-api/pull/765
fixes bug introduced by the confluence of this ticket and fecfile-web-app#1662

**Comment by mjtravers** [comment]
Moving ticket back to CR for review bug fix and to add screenshots for QA.

**Comment by mjtravers** [comment]
Passes CR, Sening to QA.
Screenshots for QA:

Here is the error message "manufactured validation error to test logs" showing in the log out put on the server:
<img width="549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3puQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea01db80ad450836757bebbcf89e5352565acb04/image.png" alt="image.png" />

Here is the error message showing in the browser:
<img width="589" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f317cca9df28b93918685f18ac803f70b7e4ca98/image.png" alt="image.png" />

All other types of errors (Non-Validation errors) should be displayed to the server log but not sent to the browser.

Here is a screenshot of an error that shows up on the server:
<img width="585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0cf05b4b4847e2093f976fa6660c78c1cb911be/image.png" alt="image.png" />

And here is a screenshot showing that the error correctly does not get sent to the browser:
<img width="668" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2efc2df7fd62dbff73cc219fc87c53641056da47/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review verified visual of the screenshots, per DEV comment above.

QA Review Completed. Moved to Stage Ready.
