### ISSUE TITLE
Create a repeatable process to generate a database UML diagram

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#70]
Use Django to generate a UML diagram of the database and create a repeatable and documented process on how to run it so the the team can generate the diagram from time to time.

First, find a new tutorial or documentation  on how to use the extension.

Here are instructions on how to generate a UML diagram by leveraging a Django extension:
https://simpleit.rocks/python/django/generate-uml-class-diagrams-from-django-models/

**Acceptance Criteria**
- A UML diagram of the database schema
- Instructions in the README on how to generate the UML diagram

**Comment by MitchellTCG** [comment]
Per Laura:

Laura Beaufort:slack_call:  9:19 AM
I think API #70 maybe we say database documentation is in the Django models and move on
