### ISSUE TITLE
Strategy for monitoring expiration dates of private keys for login / rotating private keys without downtime (current keys expire Fall 2024)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#703]

**Comment by lbeaufort** [comment]
I think our current keys may expire in 7 months

**Comment by lbeaufort** [comment]
From https://developers.login.gov/production/#certificate-rotation-process: 

Certificate Rotation Process
If you are rotating your application’s public/private keypair, or want to add an additional public certificate, please follow the instructions below to add the new certificate to your application’s Login.gov configuration.

Please note that from the time you notify Login.gov of your intent to rotate certificates, it can take up to 2 weeks for the new certificate to be available in production.

Follow this process to initiate certificate rotation:
For OIDC integrations or SAML integrations sending signed requests:
- Add the new certificate to the application dashboard configuration.
- Contact Login.gov technical support and request certificate addition.
- Once certificate deployment is confirmed, rotate the key pair at your convenience.
- Once the new key pair is in use, please submit a request to remove the old certificate.

**Comment by lbeaufort** [comment]
Also, found this helpful documentation for another project: https://github.com/GSA/data.gov/wiki/Login.gov-SAML-certificate-rotation-steps

**Comment by mjtravers** [comment]
This ticket was merged into #110. Closing ticket.
