### ISSUE TITLE
Use names/committee endpoint on FEC API

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#704]
When the system needs only name info for an fec committee, hit `https://api.open.fec.gov/v1/names/committees/` instead of `https://api.open.fec.gov/v1/committees/`.

**Comment by mjtravers** [comment]
@toddlees Is this ticket OBE? See here: https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/settings/base.py#L371

**Comment by toddlees** [comment]
> [@toddlees](https://github.com/toddlees) Is this ticket OBE? See here: https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/settings/base.py#L371

Seems so 👍

**Comment by AureliaKhorsand** [comment]
Closing as OBE.
