### ISSUE TITLE
Remove `wait_for_db.py` command from Docker file and deploy commands

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#71]
The `wait_for_db.py` command is most likely not needed for local because in docker-compose the API requires the db and in cloud.gov the database service should be running (and if it's not, we have bigger problems). It's also in the Circle config.

### Acceptance Criteria ### 

- Deployment to cloud.gov does not fail due to database availability issues
- Spin up of web-api docker-compose containers does not fail due to database availability issues

**Comment by mjtravers** [comment]
API passes unit tests and starts up with database properly initialized
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3505/workflows/6bf99234-a198-47f9-b8f3-65b1d923d0c5/jobs/10587


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/ada379e6-a375-4035-9f87-1f48d14fc7d2)

Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/1be23bab-8c3e-4573-8afe-973f717f6b4f)

QA Review Completed.   Moved to Stage Ready.
