### ISSUE TITLE
Move all API and web services settings to manifest files or creds service

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#734]
Business Reason 

As a developer, I will be able to delete applications so that I can deploy with zero downtime and address cloud.gov platform issues.

### QA Notes ###
 
  
 **App persistence**
Application environment variables will disappear if the application is deleted. We should move non-sensitive app settings (like `FEC_AGENCY_ID`) to manifest files (or app settings, as appropriate), and sensitive credentials to credentials service.  We should be able to delete and re-deploy the application. As it stands, we would lose any environment variables/config not stored in the credentials service or the manifests.

**Buildpack cache**

The buildpack cache in CF is always per-app and foundation-wide. It can only be erased by deleting the app or dropping all cache artifacts on the platform. Source: https://lists.cloudfoundry.org/g/cf-dev/topic/buildpack_cache/22187254

In general, the BLOB store manages it's own storage and cleans up after itself. There are two exceptions: the build pack cache and the resource cache. These are allowed to grow and have no automated cleanup, which can cause the build to fail. We can't manually clean up these two caches ourselves because we're not platform admins. 

Instead, we can do a zero-downtime deploy by renaming the app, deploying, and unmapping the renamed app:

```
cf rename fecfile-web-api fecfile-web-api-old
(deploy with circle, which creates fecfile-web-api
cf delete fecfile-web-api-old
```

Application environment variables will disappear if the application is deleted. We should move non-sensitive app settings (like `FEC_AGENCY_ID`) to manifest files (or app settings, as appropriate), and sensitive credentials to credentials service.  We should be able to delete and re-deploy the application. As it stands, we would lose any environment variables/config not stored in the credentials service or the manifests.

Front end manifests:
- [x] deploy-config/fecfile-web-app-dev-manifest.yml
- [x] deploy-config/fecfile-web-app-prod-manifest.yml
- [x] deploy-config/fecfile-web-app-stage-manifest.yml

Back end manifests:
- [x] manifests/manifest-dev-api.yml
- [x] manifests/manifest-dev-web-services.yml
- [x] manifests/manifest-prod-api.yml
- [x] manifests/manifest-prod-web-services.yml
- [x] manifests/manifest-stage-api.yml
- [x] manifests/manifest-stage-web-services.yml

Remove extraneous `fecfile-web-api` and `fecfile-web-services` environment variables after deploy:
- [x] DEV
- [ ] STAGE
- [ ] PROD

From: https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html
>Do not use user-provided environment variables for security-sensitive information such as credentials. They might unintentionally show up in cf CLI output and Cloud Controller logs. Use [user-provided service instances](https://docs.cloudfoundry.org/devguide/services/user-provided.html) instead. The system-provided environment variable [VCAP_SERVICES](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP_SERVICES) is properly redacted for user roles such as Space Supporter and in Cloud Controller log files.

## Dev notes ##
Look for opportunities to remove unused settings (`FRONTEND_URL`?)

## QA Notes ##
Links to the manifests files showing the added environment variables will be provided.

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

**Comment by lbeaufort** [comment]
@mjtravers thanks for fleshing this out! Noting for context that yesterday @dheitzer and I were discussing options for implementing architecture changes with zero downtime which would require us to manually delete the old version of the app, which would be blocked until we make these changes.

**Comment by mjtravers** [comment]
The TEST_COMMITTEE_PASSWORD and WEBPRINT_EMAIL variables are to be moved into the credentials service as well.

Sending ticket back to In Progress.

**Comment by dheitzer** [comment]
Moved the following to the credential services in all environments and verified functionality:

- TEST_COMMITTEE_PASSWORD
- WEBPRINT_EMAIL
- OIDC_RP_CLIENT_SECRET

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

For QA: Passes unit tests
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3711/workflows/1b39e898-d733-439e-87fb-0b1887d58ec9/jobs/11188


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/b5ff2ab9-d56c-4f8c-bd82-e48ec3bccac5)

**Comment by WiseQA** [comment]
Per DEV visual inspection of Unit Tests passing for this ticket.

QA Review Completed.  Moved to Stage Ready.
