### ISSUE TITLE
Correct contacts model codes

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#76]
The ContactType and CandidateOffice classes in the Contact model need to be updated to their FEC codes

Contact Type Codes:

  Committee = COM

  Organization = ORG

  Individual = IND

  Candidate = CAN

Candidate Office Codes:

  House = H

  Senate = S

  Presidential = P

Techinical Tasks

*   Update fecfiler/contacts/models.py ContactType class and CandidateOffice class
*   Update fecfiler/contacts/models.py so that CharField(max_length=3) for type property and CharField(max_length=1) for candidate_office property
*   In web-app, update app/shared/contact.model.ts file to update enum values for both ContactTypes and CandidateOfficeTypes.
*   Add label pipe (commented out) back into table  field in app/contacts/contact-list/contact-list.component.html file
*   Update dev, stage, prod databases using migrations if necessary with following query:

update contacts set type = 'COM' where type = 'Committee';

  update contacts set type = 'CAN' where type = 'Candidate';

  update contacts set type = 'ORG' where type = 'Organization';

  update contacts set type = 'IND' where type = 'Individual';

  update contacts set candidate_office = "P" where candidate_office = 'Presidential';

  update contacts set candidate_office = 'H' where candidate_office = 'House';

  update contacts set candidate_office = 'S' where candidate_office = 'Senate';

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-345](https://fecgov.atlassian.net/browse/FECFILE-345)

**Comment by AureliaKhorsand** [comment]
**3/16/22 Refinement Meeting:** Laura recommends a custom migration, rather than manual changes to the database. Matt updated the ticket.

**Comment by mjtravers** [comment]
This ticket is OBE. Work to fix the contact codes was completed in ticket [api#72](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/72)

Closing ticket
