### ISSUE TITLE
Vulnerability Patch - Django < 4.2.10

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#763]
api is vulnerable to https://data.safetycli.com/v/64976/97c/
upgrade to at least Django 4.2.10

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by toddlees** [comment]
Unit tests pass:<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2053f1e683bcbaabec337a1aff902eb9e699cfe/image.png" alt="image.png" />

**Comment by MitchellTCG** [comment]
### QA review consisted of a visual inspection of credential services in cloud.gov for this ticket per DEV.
<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkxJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50b77169a0f0a2bb9aca690e5f78071aeba6b67f/image.png" alt="image.png" />

### QA Review Completed. Moved to Stage Ready.
