### ISSUE TITLE
Increase API app memory to 2GB/instance

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#781]
### Business Reason ### 

As a technical requirement, API app memory needs to be increased to 2GB/instance in order to support application performance. 

From cloud.gov support:

> Based on what statistics I am seeing with regards to average CPU usage with regards to CPU entitlement I believe that the performance for the fecfile-web-api application in the fecfile-fecfileonline-prototyping org (for the prod, stage and dev spaces) would greatly benefit from increasing the application memory quota so that there is more CPU allocated to your application.

### DEV Notes
To update api cloud.gov space to 2GB, the manifest files in the repo.
Here: https://github.com/fecgov/fecfile-web-api/tree/develop/manifests

`cf cpu-entitlement <APPNAME>`

Check:
- [x] Django app
- [x] Web services

**Comment by lbeaufort** [comment]
## fecfile-web-api (big spikes)
### dev
|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  |  28.63%  |    26.64% |
|#1  |  27.81%   |    26.40% |

WARNING: Instance #0 was over entitlement from 2024-04-04 13:40:17 to 2024-04-04 13:59:32
WARNING: Instance #1 was over entitlement from 2024-04-04 13:40:39 to 2024-04-04 14:06:24

### stage
|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 37.70%   |    38.85% |
|#1  |  36.96%   |   36.53% |

WARNING: Instance #0 was over entitlement from 2024-04-03 11:40:54 to 2024-04-03 12:14:24
WARNING: Instance #1 was over entitlement from 2024-04-03 11:03:43 to 2024-04-03 11:32:13

### prod

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 33.12%  |     31.39% |
|#1  |  13.76%   |    12.87% |

WARNING: Instance #0 was over entitlement from 2024-04-03 11:40:53 to 2024-04-03 12:02:53
WARNING: Instance #1 was over entitlement from 2024-04-03 11:08:43 to 2024-04-03 11:25:28

## fecfile-web-services
### dev

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 40.92%   |     38.34% |
|#1  |  43.21%   |    42.31% |

WARNING: Instance #0 was over entitlement from 2024-04-04 13:42:11 to 2024-04-04 13:46:26
WARNING: Instance #1 was over entitlement from 2024-04-04 13:42:17 to 2024-04-04 13:47:02

### stage

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 43.45%    |    44.92% |
|#1  |  40.95%   |    44.08% |

WARNING: Instance #0 was over entitlement from 2024-04-03 11:17:13 to 2024-04-03 11:22:43
WARNING: Instance #1 was over entitlement from 2024-04-03 11:03:14 to 2024-04-03 11:08:14

### prod

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 45.06%      |    45.80% |
|#1  |  42.01%   |    43.20% |


WARNING: Instance #0 was over entitlement from 2024-04-03 11:30:48 to 2024-04-03 11:38:18
WARNING: Instance #1 was over entitlement from 2024-04-03 11:08:23 to 2024-04-03 11:13:08

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with DEV successful deployment of memory upgrade.

Moved to Stage Ready.
