### ISSUE TITLE
SPIKE: Test `CONN_MAX_AGE` setting for performance improvement. 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#787]
Look at `CONN_MAX_AGE` settings and do tests to see if changing them improves performance and reliability.

Number of connections is quite low https://devcenter.heroku.com/articles/python-concurrency-and-database-connections#persistent-connections 

From https://pypi.org/project/dj-database-url/:
>conn_max_age sets the [CONN_MAX_AGE setting](https://docs.djangoproject.com/en/stable/ref/settings/#conn-max-age), which tells Django to persist database connections between requests, up to the given lifetime in seconds. If you do not provide a value, it will follow Django’s default of 0. Setting it is recommended for performance.

https://github.com/fecgov/fecfile-web-api/pull/786

DEV NOTES
Take performance metrics for before/after connection pooling is started.

**Comment by lbeaufort** [comment]
Note - we'll need to take a look at this setting if we move to async gunicorn workers. Connections remain fixed based on the number of gunicorn workers (one connection per worker, and some basic connections puts my local at 15 regardless of the `conn_max_age` setting - this setting just keeps the connection open until the specified time. 

- [] Confirm postgres timeout on cloud.gov is 0 (no timeout set): https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT

**Comment by mjtravers** [comment]
For QA:

Screenshot of setting before change. Note the the 'CONN_MAX_AGE': 0
![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/9d07ea85-a90c-4d53-bace-9f27559ce1f3)

Screenshot of setting after change. Note the the 'CONN_MAX_AGE': 600
![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/fefddfe7-d7bf-4aa5-95c9-65595e9b19f8)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified as inspection per DEV.

Screenshot of setting after change. Note the the 'CONN_MAX_AGE': 600

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/8aaebd03-d35c-464a-95bc-afbe228d5a18)
_______________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
