### ISSUE TITLE
Put guards on non-login API endpoints

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#79]
Only logged in users should be able to get to API endpoints other than the login endpoints.

## Task ##
Used the Django Rest Framework and best practices with the rest framework to block non-logged in users from accessing endpoints other than the log on endpoints.

## Acceptance Criteria ##
- As an anonymous users, I receive a 401 Not Authenticated response when requesting non-login API endpoints
- API documentation should be available to unauthenticated users

**Comment by AureliaKhorsand** [comment]
**3/23/22 Refinement Meeting:** Added a note that API documentation should be public. Discussed that it may be better to wait for login.gov implementation, added blocker.

**Comment by mjtravers** [comment]
This has been covered by a previous ticket. OBE and closing ticket.
