### ISSUE TITLE
FECFile demo - create 2 demo accounts in `stage` environment

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#790]
### In production environment:
**Account 1:**
- [ ] New Committee Account for Demo – Can we use a PAC rather than a party committee? 
- [ ] Filing Frequency of Committee – Is it possible to have a committee that isn’t terminated and is instead active with a monthly or quarterly filing frequency?  We may need to coordinate with EFO to see if this is possible.
- [ ] Committee administrator user

**Account 2:**
- [ ] (after account creation) through application, add different user for same committee account - Login only, show 2FA

### Additional tasks: 

- [ ] Contacts – Demo account will likely need to have some previously added contacts.  FEC can add the contacts once a new demo account has been created
- [ ] Transactions – Likely should include previously entered transactions, which will allow the demo to show aggregations for individual donors and for SP/DSP
- [ ] Efiling Password – We will need to obtain a password if we plan on demonstrating that a report can be uploaded to EFO.  Will likely need to coordinate with EFO if we can create a new account for a PAC.

**Comment by MitchellTCG** [comment]
Work completed in #789

**Comment by lbeaufort** [comment]
Closing in favor of https://github.com/fecgov/fecfile-web-api/issues/789
