### ISSUE TITLE
Export Zenhub-hosted images with ticket, URL, and image information

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#796]
Before we lose access to Zenhub-hosted data, please export Zenhub-hosted images with ticket, URL, and image information.

**Comment by AureliaKhorsand** [comment]
Uploaded files to Google Drive [here](https://drive.google.com/drive/folders/1RS7MJgYBSn3duf9MTrM_dMLgf5AiEkoX). Moving to QA review - no codes changes so from BA/Dev perspective, ready for Stage Ready.

**Comment by WiseQA** [comment]
QA review verified images displaying (wireframes, screenshots for testing),   No further QA review on this ticket.

Moved to Stage Ready.
