### ISSUE TITLE
Update API readme to instruct devs to install Black Formatter and add config

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#798]
### Business Reason ### 

As a developer, I will be able to set up Black Formatter so that my code will follow the same formatting
as other developers on my team.  By using Black Formatter with the same configuration as the other developers, I will make the code base more consistent and reduce noise in code reviews that may distract from actual logic changes.

### Acceptance Criteria ### 

- [x] Readme will have language instructing the developer to install and run Black Formatter
- [x] A configuration file will be committed to the code base so that Black Formatter can be run with the same parameters for every developer [Black configuration](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

## QA NOTES ##
Write up is found in the repository landing page under the section: "Code formatting"
https://github.com/fecgov/fecfile-web-api


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/794825d8-7aec-4e27-a61c-5fe01067fae8)
