### ISSUE TITLE
Add code coverage report to Python code

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-web-api#8]
**User Story**
As a dev/QA,
I would like to see a code coverage report on the Python application code
so that our project will complete our QASP requirements

**Repos**
- fecfile-api
- fecfile-image-generator

**Acceptance Criteria**
- [x] Code coverage should run in the CI pipeline
- [x] Coverage totals will be generated based on unit test coverage
- [x] Unit tests should fail if total coverage does not meet a _configurable_ level (default to 85%)
- [x] Coverage report saved to SonarCloud

**QA:** To view a code coverage report go [here](https://app.circleci.com/pipelines/github/fecgov/fecfile-image-generator/25/workflows/51a84681-089e-4951-8228-bfc9a643fc2b/jobs/42) and expand the "Run tests, save a coverage report, and save coverage percentage" section to see the output of the coverage process.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/2/22:** Updated ticket to be specific to Python code, and added AC to indicate saving coverage report to SonarCloud. Pointed at 3.

**Comment by WiseQA** [comment]
Per acceptance criteria unit test will fail for this ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/960b6461-c177-4662-a116-5cea631504f2)

Coverage report saved:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3c6f1906-5619-4674-8609-5507a639c03b)

QA review completed.  Moved to Stage Ready.
