### ISSUE TITLE
Upgrade Django past vulnerability

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#803]
### Business Reason ### 

New vulnerability found with Django. https://data.safetycli.com/v/65771/97c/. We need to upgrade to remedy it and to pass dependency checks.

### Acceptance Criteria ### 

Upgrade api and oidc projects past vulnerability.

- [x] Upgrade api Django to 4.2.11
- [x] Upgrade oidc Django to 4.2.11
- [x] Point api's oidc dependency to commit hash with correct Django version.
- [x] Remove from safety.dependency.ignore

**Comment by mjtravers** [comment]
Unit tests passing after Django upgrade:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/761161b1-ec1a-4148-9049-84fa803e64fc)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

Moved to Stage Ready.
