### ISSUE TITLE
BUG - Unable to pull forward loan transactions that have a memo text.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#806]
The e2e tests reported a failure to save schedule C loans to the database.

The e2e test that failed is: 'should test new C1 - Loan Agreement for existing Schedule C Loan'

The error on the backend is:

`fecfile-api            | [error    ] Error: Cannot assign "UUID('fb80f43f-2514-4dc7-9369-72ab96e37fcd')": "Transaction.memo_text" must be a "MemoText" instance. [fecfiler.utils] ip=172.26.0.1 request_id=ccca97bf-e49f-420f-baee-7f4670033759 user_id=1cb79553-a0e6-43f2-b182-f102eca4a043`

The issue appears to be the loan pull forward code needs a fix for schedule C transactions.

### QA NOTES ###
Should pass e2e test that is currently failing.

**Comment by mjtravers** [comment]
For QA. Screenshot of passing tests for loans that were previously failing:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/bc078b31-83f2-4212-a0d6-892b825f3c8a)

**Comment by mjtravers** [comment]
Passed CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified per DEV unit tests passing.

Moved to Stage Ready.
