### ISSUE TITLE
SPIKE: research high celery (`fecfile-web-services`) CPU

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#807]
Investigate CPU spikes in celery worker in Cloud.gov

### dev

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 40.92%   |     38.34% |
|#1  |  43.21%   |    42.31% |

WARNING: Instance #0 was over entitlement from 2024-04-04 13:42:11 to 2024-04-04 13:46:26
WARNING: Instance #1 was over entitlement from 2024-04-04 13:42:17 to 2024-04-04 13:47:02

### stage

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 43.45%    |    44.92% |
|#1  |  40.95%   |    44.08% |

WARNING: Instance #0 was over entitlement from 2024-04-03 11:17:13 to 2024-04-03 11:22:43
WARNING: Instance #1 was over entitlement from 2024-04-03 11:03:14 to 2024-04-03 11:08:14

### prod

|  instance   | avg usage |  curr usage |
|-|--|-|
|#0  | 45.06%      |    45.80% |
|#1  |  42.01%   |    43.20% |

WARNING: Instance #0 was over entitlement from 2024-04-03 11:30:48 to 2024-04-03 11:38:18
WARNING: Instance #1 was over entitlement from 2024-04-03 11:08:23 to 2024-04-03 11:13:08

**Comment by dheitzer** [comment]
```
cf app fecfile-web-services
```
shows the consumption of system cpu on the vm

```
cf ssh fecfile-web-services
ps -eo pcpu,pid,user,args | tail -n +2 | sort -k1 -r -n | head -10
```
shows system cpu utilization on vm per proc 

```
cf cpu-entitlement fecfile-web-services
```
shows percentage of entitlement (based on memory sizing of the app)

**Comment by dheitzer** [comment]
<h2>WITH celery running in prod</h2>

<b>entitlement cpu usage</b>:
<table>
  <tr>
    <th>Instance</th>
    <th>avg usage</th>
    <th>curr usage</th>
  </tr>
  <tr>
    <td>#0</td>
    <td>42.91%</td>
    <td>40.19%</td>
  </tr>
  <tr>
    <td>#1</td>
    <td>28.41%</td>
    <td>28.78%</td>
  </tr>
</table>
 
<b>percent of total host cpu usage</b>:
<table>
  <tr>
    <th>Instance</th>
    <th>cpu</th>
    <th>memory</th>
  </tr>
  <tr>
    <td>#0</td>
    <td>0.6%</td>
    <td>472.2M of 1G</td>
  </tr>
  <tr>
    <td>#1</td>
    <td>0.4%</td>
    <td>470.7M of 1G</td>
  </tr>
</table>



<h2>WITHOUT celery running in prod</h2>

<b>entitlement cpu usage</b>:
<table>
  <tr>
    <th>Instance</th>
    <th>avg usage</th>
    <th>curr usage</th>
  </tr>
  <tr>
    <td>#0</td>
    <td>15.32%</td>
    <td>13.49%</td>
  </tr>
  <tr>
    <td>#1</td>
    <td>14.74%</td>
    <td>11.70%</td>
  </tr>
</table>
 
<b>percent of total host cpu usage</b>:
<table>
  <tr>
    <th>Instance</th>
    <th>cpu</th>
    <th>memory</th>
  </tr>
  <tr>
    <td>#0</td>
    <td>0.2%</td>
    <td>15.4M of 1G</td>
  </tr>
  <tr>
    <td>#1</td>
    <td>0.2%</td>
    <td>15.4M of 1G</td>
  </tr>
</table>


<b>Initial thoughts</b>
This shows that while Celery uses 30% of our entitlement cpu bandwidth just idling, this actually translates to only amount to .2 - .4% of our host cpu (r6i.2xlarge with 8 cores).

**Comment by dheitzer** [comment]
@lbeaufort I'm wondering if you have any thoughts on these findings.   My thoughts are:

1. It seems to me that Celery is using a relatively low amount of cpu during idle.  Finding hardware requirements for Celery was difficult, but I did find [this recommendation from a 3rd party provider](https://docs.waldur.com/admin-guide/hardware-requirements/#waldur-mastermind-celery-worker)
2. The correlation of the cpu usage graphs for  fecfile-web-api and fecfile-web-services could be due to application restarts which temporarily spike the cpu usage of both containers which remain idle most of the time.
3.  We may need to increase the memory for fecfile-web-services since the total **with celery** exceeds 1G (assuming 1G is allocated across all instances).

**Comment by mjtravers** [comment]
No code to CR. Research findings written up in comments above.

Sending to QA.

**Comment by WiseQA** [comment]
No code change and no QA review needed on this ticket.

Moved to Stage Ready.
