### ISSUE TITLE
Turn off swagger API docs

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#812]
Business Reason

[https://fecfile-web-api-stage.app.cloud.gov/api/docs/](https://fecfile-web-api-stage.app.cloud.gov/api/docs/)

Screenshot of broken web page. [![](https://github.com/fecgov/fecfile-web-api/assets/2971785/1e43c81e-59e1-4323-a5de-d9506c14e33c)](https://github.com/fecgov/fecfile-web-api/assets/2971785/1e43c81e-59e1-4323-a5de-d9506c14e33c)

Swagger page is not functioning correctly. We should turn it off. A later ticket will fix it and turn it on.

Acceptance Criteria

*   [x] Swagger pages will no longer be available on the api
*   [x] Clear out swagger static assets that are created by swagger at runtime

### QA Notes ###

null

### DEV Notes ###

A new endpoint `/status/` has been established to provide Pingdom a suitable point to check the API's condition.  This endpoint simply returns a 200 status.

### Design ###

null

[FECFILE-195](https://fecgov.atlassian.net/browse/FECFILE-195)

**Comment by Elaine-Krauss-TCG** [comment]
New endpoint established, `/status/` which returns a standard 200 status response while not requiring authentication.

![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/56489c24-7666-4658-b442-13782a014932)

**Comment by mjtravers** [comment]
No longer blocked. Passes CR. Moving to QA.

**Comment by WiseQA** [comment]
QA review verified visual inspection per DEV screenshot above showing the successfully new endpoint established, /status/ which returns a standard 200 status response while not requiring authentication.

QA Review Completed.  Moved to Stage Ready.
