### ISSUE TITLE
Print all exceptions in log

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#815]
### Business Reason ### 

As a developer, i will be able to see stack traces for errors in the log so that i can debug user's errors

### Acceptance Criteria ### 

Exception stack traces will be printed to log while still following rules laid out in [689](https://github.com/fecgov/fecfile-web-api/issues/689) about which errors are revealed in the payload

### Dev Notes ###

We print out the message of the error here, but we need more context than the toString of `exc`
```
    if response is None:
        logger.error(f"Error: {exc}")
        return HttpResponseServerError()
```

**Comment by mjtravers** [comment]
# QA NOTES #
Screenshot of an exception printed in the log:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/406a92f3-4ed1-41c1-8407-eae80cb200db)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review visual inspection from DEV printed output.

QA Review Completed. Moved to Stage Ready.
