### ISSUE TITLE
Implement API Gateway architecture

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#816]
Blocking #780

Follow on ticket to issue #659 ( [ Unable to render embedded object: File (medium) not found. [ [![](https://camo.githubusercontent.com/5c77529fbda1ec0f786e2f4bd81359537342773a54eec8674638b84e803cc987/68747470733a2f2f666563676f762e61746c61737369616e2e6e65742f726573742f6170692f322f756e6976657273616c5f6176617461722f766965772f747970652f6973737565747970652f6176617461722f31303331353f73697a653d6d656469756d)](https://camo.githubusercontent.com/5c77529fbda1ec0f786e2f4bd81359537342773a54eec8674638b84e803cc987/68747470733a2f2f666563676f762e61746c61737369616e2e6e65742f726573742f6170692f322f756e6976657273616c5f6176617461722f766965772f747970652f6973737565747970652f6176617461722f31303331353f73697a653d6d656469756d) [ [![](https://camo.githubusercontent.com/5c77529fbda1ec0f786e2f4bd81359537342773a54eec8674638b84e803cc987/68747470733a2f2f666563676f762e61746c61737369616e2e6e65742f726573742f6170692f322f756e6976657273616c5f6176617461722f766965772f747970652f6973737565747970652f6176617461722f31303331353f73697a653d6d656469756d)](https://camo.githubusercontent.com/5c77529fbda1ec0f786e2f4bd81359537342773a54eec8674638b84e803cc987/68747470733a2f2f666563676f762e61746c61737369616e2e6e65742f726573742f6170692f322f756e6976657273616c5f6176617461722f766965772f747970652f6973737565747970652f6176617461722f31303331353f73697a653d6d656469756d) [ ![](https://camo.githubusercontent.com/5c77529fbda1ec0f786e2f4bd81359537342773a54eec8674638b84e803cc987/68747470733a2f2f666563676f762e61746c61737369616e2e6e65742f726573742f6170692f322f756e6976657273616c5f6176617461722f766965772f747970652f6973737565747970652f6176617461722f31303331353f73697a653d6d656469756d)  [ ![](https://fecgov.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium) FECFILE-238 ](https://fecgov.atlassian.net/browse/FECFILE-238 "SPIKE: Research adding rate limiting to the API") Done  | [https://fecgov.atlassian.net/browse/FECFILE-238](https://fecgov.atlassian.net/browse/FECFILE-238) "SPIKE: Research adding rate limiting to the API"] Done | [https://fecgov.atlassian.net/browse/FECFILE-238](https://fecgov.atlassian.net/browse/FECFILE-238) "SPIKE: Research adding rate limiting to the API"] Done | [https://fecgov.atlassian.net/browse/FECFILE-238](https://fecgov.atlassian.net/browse/FECFILE-238) "SPIKE: Research adding rate limiting to the API"] Done | [https://fecgov.atlassian.net/browse/FECFILE-238](https://fecgov.atlassian.net/browse/FECFILE-238) "SPIKE: Research adding rate limiting to the API"] Done ). Link to that ticket's 🔒 findings 🔒

Decide upon and implement gateway architecture to protect against denial-of-service attacks.

The different rate limiting options include:

API Umbrella - [https://github.com/NREL/api-umbrella/](https://github.com/NREL/api-umbrella/) Nginx - [https://blog.nginx.org/blog/rate-limiting-nginx](https://blog.nginx.org/blog/rate-limiting-nginx) Django - [https://www.django-rest-framework.org/api-guide/throttling/](https://www.django-rest-framework.org/api-guide/throttling/)

*   [x] Assess (using a DAR) the features and rank the proposed options -> nginx reverse proxy
*   [x] Implement chosen strategy
*   [X] Notify @AureliaKhorsand of new repo fecfile-api-proxy

### QA Notes ###

 
  
  
 null

### DEV Notes ###

 
  
  
 The following command should be run just prior to api deployment to the remove the api route and force all traffic through the proxy:
`cf unmap-route fecfile-web-api app.cloud.gov --hostname fecfile-web-api-`

Please run this just prior to api deploy in:

- [X] DEV
- [X] STAGE
- [ ] PROD

### Design ###

 
  
  
 null

[FECFILE-193](https://fecgov.atlassian.net/browse/FECFILE-193)

**Comment by AureliaKhorsand** [comment]
@lbeaufort permission to test sync for Exalate to ensure it works from Jira to GitHub and vice versa?

**Comment by AureliaKhorsand** [comment]
Added fecfile-api-proxy to the exalate scripting and confirmed it is working from both GitHub and Jira.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

Screenshots of unit tests passing:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/5928/workflows/10e17d54-6645-4d6c-bba7-6aec8a9f5ad2/jobs/20422


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/a599defd-515f-4a4c-8ae1-b2ae8a312494)


https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3789/workflows/77a38913-2b79-4bee-b4ed-e11d64a0ad32/jobs/11436


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/b6d91b7f-5140-4437-964a-92c528624d60)

**Comment by WiseQA** [comment]
QA review verified as visual inspection with DEV the unit tests passing for this ticket.

QA Review Completed.   Moved to Stage Ready.
