### ISSUE TITLE
Load test locally 150 users and 100,000 records

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#819]
Benchmark current capabilities while running the locust script with 150 users and 100000 records. Profile with Silk to identify request durations and timing within each request.

Create tickets per performance issue discovered.

Load test all schedules (locust currently only set up for schedule A)

There is a PR in progress for this ticket: [https://github.com/fecgov/fecfile-web-api/pull/882](https://github.com/fecgov/fecfile-web-api/pull/882)

Here is a spreadsheet example 🔒 Locust testing spreadsheet 🔒

### QA Notes ###

 
  
 null

### DEV Notes ###

 
  
 null

### Design ###

 
  
 null

[FECFILE-190](https://fecgov.atlassian.net/browse/FECFILE-190)

**Comment by Elaine-Krauss-TCG** [comment]
Successfully imported 99,999 records (+1 record for the testing committee account that already exists) using a fixture generated by my new script.

![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/d74e707d-acbf-49ac-aec4-8584f39a95ad)

**Comment by Elaine-Krauss-TCG** [comment]
Here's a collection of opportunities for performance boosts:

- Calculating whether or not a report can be deleted takes 500+ms per report (report serializer, can_delete method)
- Summary page calculation never completed in upwards of 10 minutes of calculating
- WIP

**Comment by Elaine-Krauss-TCG** [comment]
New tickets were created in the aftermath of this ticket:
- [Refactor Report Recalculation Flagging](https://github.com/fecgov/fecfile-web-api/issues/917#issue-2360140565)
- [Investigate non-terminating report summary calculation](https://github.com/fecgov/fecfile-web-api/issues/920#issue-2360253465)
- [Refactor Report Serialization](https://github.com/fecgov/fecfile-web-api/issues/918#issue-2360183086)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

Notes for QA: The outcome of this ticket are the notes in the comments above the the 3 new performance-related tickets listed above as well.

**Comment by WiseQA** [comment]
QA review verified per visual inspection the DEV screenshot above showing the successfully imported 99,999 records (+1 record for the testing committee account that already exists) using a fixture generated by my new script.

QA Review Completed.  Moved to Stage Ready.
