### ISSUE TITLE
Deployment should fail when migrations fail

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#82]
Currently, if migrations fail on this step: 
https://github.com/fecgov/fecfile-web-api/blob/7688b5902277f6888a32efd4fa78435a9c7955e5/bin/run.sh#L3-L4

then the deployment will continue, resulting in silent errors. We should add the migrations to the the deployment steps here: 
https://github.com/fecgov/fecfile-web-api/blob/7688b5902277f6888a32efd4fa78435a9c7955e5/bin/run.sh#L6-L7
so that failing migrations fail the deployment as well.

NOTE: Task includes updating the run.sh script in CircleCI to return an error code.

### QA NOTES ###
Here are the test results of the deployment failing (which is what we want to happen) when the run-api.sh script fails https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/880/workflows/5a22f1bf-4347-4327-bfde-c80180048ef7/jobs/2649

**Comment by WiseQA** [comment]
QA review verified as a visual inspection with DEV that the deployment failed and is displaying a Failed circle CI task as expected.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a886ea6e-436c-4307-9c55-37cdd4cf5203)

QA Review Completed.  Moved to Stage.
