### ISSUE TITLE
SPIKE: Investigate optimizations to transaction list endpoint

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#828]
The api endpoint to pull a list of transactions for display on a report's Transactions page is suboptimal. Examine where it is slow and document changes that can improve performance. 

Things to look at:
- [x] convert transaction view to materialized view
- [x] add indexes to materialized view
- [x] remove payload field not needed by transaction list page to reduce the number of queries run
- [x] move transaction amount field from schedule tables to transactions_transaction table
- [x] streamline query for /previous endpoint check
- [x] code profile /transactions endpoint to see where code is spending its time
- [x] move annotated fields not part of pagination to serializer

**Comment by mjtravers** [comment]
With materialized view in place:
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/e7113842-d25b-41c8-943d-cb9d5c1f15a7)
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/a1d7c2f3-2f23-4da8-bbe0-50ef2f3af23a)

**Comment by mjtravers** [comment]
Same setup as previous comment but looking at a 20 transactions/page list table:
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/1e685f72-664f-43f2-b4d8-486e1f04ad10)
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/d012055c-524f-471d-9f3a-7fd98148f994)

**Comment by mjtravers** [comment]
Code profile of a transaction to_representation() call
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/ce559315-6095-487e-b080-3ac01073267a)

**Comment by mjtravers** [comment]
To see if connection pooling is having any affect on reducing the time in the django code, this run was made with the materialized view in place and the code changes from #822 . The times (using the same 1 report, 20 contacts, 1,000 transactions) are the same without improvement:
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/736e2d87-3af6-4333-a3ec-71edb36331a3)
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/1060fd63-842e-404c-9530-1fe503d3c600)

**Comment by mjtravers** [comment]
Pulling the transactions into the report is an expensive query:

File fecfiler/reports/serializers.py, line 107, in to_representation

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/aad9583d-fa0a-4373-a8f1-5364639f2cce)

Are there endpoints where the report does not need the transactions or could get by with transaction ids?

**Comment by mjtravers** [comment]
Here are a few actionable tasks to change serializer code to improve performance. Due to foreign keys and Django automatically pulling foreign key records, the report, transaction, and contact serializers all influence the response time of each other:

1. The manual retrieval of the reports attached to a transaction. Investigate where we need the report attached. In the list page, it is called repeatedly for all the transactions in the same report. Can we remove it from the list page? Can we get by with report ids and have the front end request the report info if needed? 

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/e8baf49f-2416-4b2c-ba8d-db17e079b375)


2.  Adding the children object to the transaction. Didn't we change to children ids and the front end pull the child if needed? Is this needed on the list page?

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/3186a50c-3576-4124-8d32-c5eb1ea2dc76)

3. Only call the reattribution/redesignation aggregation totals if the transaction is REATTRIBUTED/REDESIGNATED. Currently, the totals are calculated regardless

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/923844da-b8a5-4faf-b866-6b37ce37a238)

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/86ac5d3b-c798-4f15-a852-f77d9bce9942)

4. In the Contacts serializer, only call the query for "has_transaction_or_report" for the endpoint of the contact list page. Only needed for contact deletion and adds unnecessary queries otherwise.

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/ab216986-1e8f-42d4-8df4-974b5043bb64)

5. See comment above about refactoring the transaction set link in the reports serializer.

**Comment by mjtravers** [comment]
Other notes:
1. Speed up single transaction update response time by not sending back updated transaction to the front end.
2.

**Comment by WiseQA** [comment]
QA review verified as a visual inspection per DEV of the changes shown DEV captured screenshots above.  Performance testing of transactions.  Per DEV speed up single transaction create/update response time.

QA Review Completed.  Moved to Stage Ready.
