### ISSUE TITLE
SPIKE: Assess test EFO-OpenFEC-FECFile closed system for F1s

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#829]
Business Reason

So a user can create a committee on their own in the test environment, we need to assess the feasibility of EFO writing F1's filed on their test environment to OpenFEC's test environment, so that FECFile can retrieve the data when registering a committee account. The data should be restricted to one (sensitive) API key, as to not be available to the public

Acceptance Criteria

Find out if the following are possible:

*   [x] can Test EFO write filed F1s to Test OpenFEC dev postgres database (or all 3 environments if it's easier/simpler/less risky) similar to the inserts for the `real_efile.f1` table, but in a **different table** or schema? ➡ yes, they need the table info. Since we want to restrict it to one API key, we need this to be in the staging database
*   [x] can dev OpenFEC make test F1s available to (only) Test FECFile via their API

### QA Notes ###

 
  
 null

### DEV Notes ###

 
  
https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/openfec/views.py#L61
https://github.com/fecgov/fecfile-web-api/blob/6b614b504bc00d1702583bff39895d4f3d6fc2c7/django-backend/fecfiler/committee_accounts/views.py#L211-L220

### Design ###

 
  
 null

[FECFILE-187](https://fecgov.atlassian.net/browse/FECFILE-187)

**Comment by mjtravers** [comment]
No code to review or QA to be done. This ticket was to get the process going to have the OpenFEC table created when a Form 1 is submitted to Test EFO.

**Comment by AureliaKhorsand** [comment]
@mjtravers I'm assuming that the self-service account creation workflow tickets will include actually connecting to this, right?

**Comment by WiseQA** [comment]
No QA review needed on this ticket per DEV comment that no code to review or QA to be done. This ticket was to get the process going to have the OpenFEC table created when a Form 1 is submitted to Test EFO.

Moved to Stage Ready.
