### ISSUE TITLE
Change Mary's Committee  (C00100479) Type for testing

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#831]
So that Shelly can test 
https://github.com/fecgov/fecfile-web-app/issues/404
https://github.com/fecgov/fecfile-web-app/issues/1472
https://github.com/fecgov/fecfile-web-app/issues/1659
https://github.com/fecgov/fecfile-web-app/issues/1800

Change committee types for C00100479 to match whichever ticket shelly is testing at the time so that she can see the correct transaction types.

**Comment by MitchellTCG** [comment]
@dheitzer I assigned this to you.

**Comment by dheitzer** [comment]
Thanks @MitchellTCG.  Adding updates as comments in the respective tickets as this work is completed.

**Comment by mjtravers** [comment]
Three committees were set up for Shelly's login account so she no longer needs to access Mary's account. This ticket is OBE.
