### ISSUE TITLE
Remove redundant inherited itemized code

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#837]
The code that determines whether a child transaction is itemized based on its parent has been moved from the .fec composer code to the transaction manager.

This ticket is to remove the redundant code determining the itemize status:
https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/dot_fec/dot_fec_composer.py#L51-L64

![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/4917751f-a3a4-4ea0-8102-3e69df8cbf02)

## DEV NOTES ##
- The parent calendar_ytd_per_election_office for the Schedule E will need to be determined differently:

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/75199161-3db8-48f3-ab9b-969202387fce)

- Verify unit tests in place for testing child itemization

## QA NOTES ##
Child transactions should have the same itemization status as parent

**Comment by toddlees** [comment]
passes CR moving to QA

**Comment by WiseQA** [comment]
@mjtravers @toddlees can we please add unit tests for verification.   See DEV notes above to add unit tests.  Thanks

**Comment by WiseQA** [comment]
QA review verified visual inspection of Unit Tests per DEV.

QA Review Completed.   Moved to Stage Ready.
