### ISSUE TITLE
Remove DRF form display for API calls

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#849]
If you run any authenticated query in the browser (log in, inspect, open in new tab) and you'll see the DRF API data entry-type form. We should disable this.

Steps to reproduce:

1\. log in
 2\. open developer console
 3\. got to Network tab
 4\. right click api url in network list and select "Open in new tab"

POSSIBLE SOLUTION: [https://stackoverflow.com/questions/11898065/how-to-disable-admin-style-browsable-interface-of-django-rest-framework](https://stackoverflow.com/questions/11898065/how-to-disable-admin-style-browsable-interface-of-django-rest-framework)([https://stackoverflow.com/questions/11898065/how-to-disable-admin-style-browsable-interface-of-django-rest-framework](https://stackoverflow.com/questions/11898065/how-to-disable-admin-style-browsable-interface-of-django-rest-framework)) 

![image-20240605-175213.png](/attachments/11344?name=image-20240605-175213.png) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-179](https://fecgov.atlassian.net/browse/FECFILE-179)([https://fecgov.atlassian.net/browse/FECFILE-179](https://fecgov.atlassian.net/browse/FECFILE-179)))

![Screenshot 2024-04-25 at 2 21 53 PM]([https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2](https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2)([https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2](https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2)))

1\. 1\. QA Notes ##
 A URL will be provided to test in a tab that the form is not appearing for the URL 
 1\. QA Notes ###
 Steps to reproduce:

1\. log in
 2\. open developer console
 3\. got to Network tab
 4\. right click api url in network list and select "Open in new tab"

![Screenshot 2024-04-25 at 2 21 53 PM]([https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2](https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2)([https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2](https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2)))

1\. 1\. QA Notes ##
 A URL will be provided to test in a tab that the form is not appearing for the URL 
 1\. DEV Notes ###
 null
 2\. Design ###
 null

1.  1.  1.  QA Notes ###

 Steps to reproduce:

1\. log in
 2\. open developer console
 3\. got to Network tab
 4\. right click api url in network list and select "Open in new tab"

![Screenshot 2024-04-25 at 2 21 53 PM]([https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2](https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2))

1.  1.  QA Notes ##
         A URL will be provided to test in a tab that the form is not appearing for the URL

1.  1.  1.  DEV Notes ###

 null

1.  1.  1.  Design ###

 null

### QA Notes ###

 
 Steps to reproduce:

1. log in
2. open developer console
3. got to Network tab
4. right click api url in network list and select "Open in new tab"

![Screenshot 2024-04-25 at 2 21 53 PM](https://github.com/fecgov/fecfile-web-api/assets/31420082/41ac5a05-05f5-4e3d-a9e1-d44b2a2b3ab2)

## QA Notes ##
A URL will be provided to test in a tab that the form is not appearing for the URL

### DEV Notes ###

 
 null

### Design ###

 
 null

[FECFILE-179](https://fecgov.atlassian.net/browse/FECFILE-179)

**Comment by mjtravers** [comment]
Confirmed that a web form is not displayed when a browser hits an api endpoint:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/ea730932-2345-44b4-a205-cbfe61511467)


Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review completed per DEV that confirmed that a web form is not displayed when a browser hits an api endpoint (see screenshot above).

Moved to Stage Ready.
