### ISSUE TITLE
Fix case sensitive email match for committee registering

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#859]
***Business Reason***
 As a committee owner, I will be able to register my committee when my email on the f1 is in a different case than my email on FECFile online so that I can register my committee

***Acceptance Criteria***
 Given that my email on FECFile Online is `fakeemail@gmail.com` and my email on the F1 is `FAKEEMAIL@GMAIL.COM` the system will still match them and allow me to register the committee

### QA Notes ###
 
  
 null

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

**Comment by Elaine-Krauss-TCG** [comment]
Successfully added myself to a test committee with an f1_email of "TEST@TEST.com" even though my account was using the test email: "test@test.com"

![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/aa5f3f44-53e3-4205-8950-b2aff5212883)
![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/b0ff8c9a-91c1-48d0-a9a4-9465936ac95c)
![Image](https://github.com/fecgov/fecfile-web-api/assets/104506225/d8f97aef-0623-4075-b59e-8dc0bbc47019)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with DEV as shown in screenshots case sensitive email match for committee registering,

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/e4806cb0-92ba-47e4-8466-2bfce5df902e)

_________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/a83c9a91-78cf-46ff-b1e2-c8ce4334df2b)

________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
