### ISSUE TITLE
Remove static and staticfiles directories from api

### ISSUE THREAD

**Issue by toddlees** [fecgov/fecfile-web-api#87]
Now that we have DRF Spectacular supporting our api docs, we no longer need any of the content in static/ and staticfiles/

Remove these directories and their content from the codebase

## Acceptance Criteria ##
- a user is still able to access https://fecfile-web-api-dev.app.cloud.gov/api/docs/ after the files have been removed

**Comment by mjtravers** [comment]
This is OBE. The directories were removed and tested as part of [api#7](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/7)

Closing ticket.
