### ISSUE TITLE
Code fixes in preparation of demo

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#872]
The following patches were made to STAGE in preparation for the demo on May 8:

1. Updated the state values in the mock committee data that had erroneously full state names rather than 2-letter abbreviation. This was disabling the "Confirm information" button on the step 1 submission screen.
2. Fixed the control logic that calculates the summary values that are dependent on the COH value of reports. Values were not being calculated when the COH value was $0.00.
3. Fixed alignment of the "Confirm information" button with the HR lines on the step 1 submission screen.
4. Fixed the dotted underline wrapping on the login committee select list when committee names wrap to multiple lines.
5. The summary page and print preview page were not showing. The issue was found by investigating the server logs. Fixed the underlying issue when calculating fields associated with the cash on hand when lines 6a or 6b did not have a value. The summary values would not appear on the Print Preview page.

**QA Notes**
1. Test by confirming affected committees are now able to click the "Confirm Information" button on submit step 1 page.
2. Test by confirming if COH is set to $0, future reports have COH values displaying on their summary page.
3. "Confirm information" button right side should align vertically with HR lines across form.
4. Test by viewing a committee name that wraps on the committee select page.
5. Test by confirming summary page and print preview page appear.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by mjtravers** [comment]
Screen shot of #4, the dotted underline with line wrapping:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/b576dc58-4247-4322-8d26-cd4820852f0d)

**Comment by WiseQA** [comment]
**QA review verified the following fixes were implemented and tested on STAGE for demo**
- [ ] Test by confirming affected committees are now able to click the "Confirm Information" button on submit step 1 page.
- [ ] Test by confirming if COH is set to $0, future reports have COH values displaying on their summary page.
- [ ] "Confirm information" button right side should align vertically with HR lines across form.
- [ ] Test by viewing a committee name that wraps on the committee select page.  (Visual with DEV see screenshot above)
- [ ] Test by confirming summary page and print preview page appear.
