### ISSUE TITLE
Add summary page calculation trigger to print preview and report submit process.

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#878]
### Business Reason ### 

As a user, I want the F3X summary information to display in my print preview and added to my report submission even if I have not viewed the summary page.

### Acceptance Criteria ### 

**If** doing a print preview on a F3X
**When** I skip viewing the summary page
**Then** the summary data will appear correctly in the print preview.

Currently, there are paths through the UI that allows a user to submit a report or view a report without the summary data being calculated.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on STAGE.

**Comment by WiseQA** [comment]
QA review verified summary page calculation on print preview and report submit process.

QA Review Completed.  Moved to Stage Ready.
