### ISSUE TITLE
Reattributing a JFTransfer with a JF Transfer Memo fails

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#881]
To reproduce the problem:

Create a JF Transfer and a JF Transfer Memo for that JF Transfer. Then click on "Reattribute" on the JF Transfer.

![image-20240531-133823.png](/attachments/11320?name=image-20240531-133823.png) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-164](https://fecgov.atlassian.net/browse/FECFILE-164))

 [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-164](https://fecgov.atlassian.net/browse/FECFILE-164))

![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552](https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552))

Fill out the Reattribution form. Then click the "Save" button. You will see a pop-up showing a 500 Internal Server error.

![image-20240531-133936.png](/attachments/11319?name=image-20240531-133936.png)

![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02](https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02))

***DEV Notes***
 Here is the error being thrown on the backend:

![image-20240531-134008.png](/attachments/11318?name=image-20240531-134008.png)

![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537](https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537))

This fix for this should address all transaction types that have children and cover both REATTRIBUTION and REDESIGNATION.

@MitchellTCG @mjtravers assigned to Sprint 42 and pointed 3 points. Error found in Sprint 41.

***QA Notes***

1.  1.  1.  QA Notes ###
             Create a JF Transfer and a JF Transfer Memo for that JF Transfer. Then click on "Reattribute" on the JF Transfer.

![image-20240531-200105.png](/attachments/11328?name=image-20240531-200105.png)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552](https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552))

Fill out the Reattribution form. Then click the "Save" button. You will see a pop-up showing a 500 Internal Server error.

![image-20240531-200127.png](/attachments/11329?name=image-20240531-200127.png)

![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02](https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02))

***DEV Notes***
 Here is the error being thrown on the backend:

![image-20240531-200154.png](/attachments/11330?name=image-20240531-200154.png)

![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537](https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537))

This fix for this should address all transaction types that have children and cover both REATTRIBUTION and REDESIGNATION.

@MitchellTCG @mjtravers assigned to Sprint 42 and pointed 3 points. Error found in Sprint 41.

***QA Notes***

1.  1.  1.  DEV Notes ###
             null
        2.  Design ###
             null
        3.  QA Notes ###

 Create a JF Transfer and a JF Transfer Memo for that JF Transfer. Then click on "Reattribute" on the JF Transfer.
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552](https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552))

Fill out the Reattribution form. Then click the "Save" button. You will see a pop-up showing a 500 Internal Server error.
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02](https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02))

***DEV Notes***
 Here is the error being thrown on the backend:
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537](https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537))

This fix for this should address all transaction types that have children and cover both REATTRIBUTION and REDESIGNATION.

@MitchellTCG @mjtravers assigned to Sprint 42 and pointed 3 points. Error found in Sprint 41.

***QA Notes***

1.  1.  1.  DEV Notes ###

 null

1.  1.  1.  Design ###

 null

### QA Notes ###
 
  
 Create a JF Transfer and a JF Transfer Memo for that JF Transfer. Then click on "Reattribute" on the JF Transfer.
![image](https://github.com/fecgov/fecfile-web-api/assets/94924171/af2be591-2d0b-47ae-a3d8-1dbf04a6c552)

Fill out the Reattribution form. Then click the "Save" button. You will see a pop-up showing a 500 Internal Server error.
![image](https://github.com/fecgov/fecfile-web-api/assets/94924171/b3c89529-462c-40e6-838b-081e25b96f02)

**DEV Notes**
Here is the error being thrown on the backend:
![image](https://github.com/fecgov/fecfile-web-api/assets/94924171/c5739297-7f44-497f-94db-acbfdc848537)

This fix for this should address all transaction types that have children and cover both REATTRIBUTION and REDESIGNATION.

@MitchellTCG @mjtravers assigned to Sprint 42 and pointed 3 points. Error found in Sprint 41.

**QA Notes**

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

**Comment by WiseQA** [comment]
On hold until QA and DEV review if this is e2e testing or a functionality break.

**Comment by WiseQA** [comment]
QA and DEV reviewed this bug and verified the error is valid.   @mjtravers as promised here's your stars :-)  - Just a little humor.

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/997c70e8-8071-42c5-83f5-201f23c21f74)

**Comment by WiseQA** [comment]
QA review verified bug fixed.

1.  Created a Joint Fundraising Transfer / Joint Fundraising Transfer Memo

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/606f7431-58c9-4192-b8c8-407ae8e0a0ad)

2.   Selected the Reattribute then filled out the Reattribution form. Upon selecting "Save" the 500 Internal Server error was not displaying. 
  This was the bug.   

QA Review Completed.

**Comment by mjtravers** [comment]
Screenshot of log when reattributing a JF Transfer with a memo:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/535469b3-63a8-4aa1-8861-26b5f1e78277)
