### ISSUE TITLE
Add exception handling to webprint submit process

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#883]
When submitting a report to the EFO WebPrint service, if there is an error with the submit process (e.g. the site is down) the error is not handled properly and the front-end gets a perpetual spinner.

The process for WebSubmit does have the error handling code and can be used as a model to implement error handling for WebPrint.

***DEV Notes***

The WebSubmit example code is here:
 [https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621](https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621))

The WebPrint code that needs refactoring is here:
 [https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0](https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0))

***QA Notes***

A dev will have to provide screenshots of database entries showing 2 states:
 1\. A webprint record with a success status that is created on a successful submit.
 2\. A webprint record with a failed status that is created on a failed submit. The dev can artificially create a failed submit by using a bad URL for webprint locally.

1.  1.  1.  QA Notes ###
             The process for WebSubmit does have the error handling code and can be used as a model to implement error handling for WebPrint.

***DEV Notes***

The WebSubmit example code is here:
 [https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621](https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621))

The WebPrint code that needs refactoring is here:
 [https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0](https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0))

***QA Notes***

A dev will have to provide screenshots of database entries showing 2 states:
 1\. A webprint record with a success status that is created on a successful submit.
 2\. A webprint record with a failed status that is created on a failed submit. The dev can artificially create a failed submit by using a bad URL for webprint locally.

1.  1.  1.  DEV Notes ###
             null
        2.  Design ###
             null
        3.  QA Notes ###

 The process for WebSubmit does have the error handling code and can be used as a model to implement error handling for WebPrint.

***DEV Notes***

The WebSubmit example code is here:
 [https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621](https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621))

The WebPrint code that needs refactoring is here:
 [https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158)
 ![image]([https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0](https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0))

***QA Notes***

A dev will have to provide screenshots of database entries showing 2 states:
 1\. A webprint record with a success status that is created on a successful submit.
 2\. A webprint record with a failed status that is created on a failed submit. The dev can artificially create a failed submit by using a bad URL for webprint locally.

1.  1.  1.  DEV Notes ###

 null

1.  1.  1.  Design ###

 null

### QA Notes ###
 
  
 The process for WebSubmit does have the error handling code and can be used as a model to implement error handling for WebPrint.

**DEV Notes**

The WebSubmit example code is here:
https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L94-L117
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/1baf6097-3c47-448a-b963-b4c02fb6f621)

The WebPrint code that needs refactoring is here:
https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/web_services/tasks.py#L154-L158
![image](https://github.com/fecgov/fecfile-web-api/assets/2971785/7e0c9dc5-6b71-4f0e-8c4b-525f08df38a0)

**QA Notes**

A dev will have to provide screenshots of database entries showing 2 states:
1. A webprint record with a success status that is created on a successful submit.
2. A webprint record with a failed status that is created on a failed submit. The dev can artificially create a failed submit by using a bad URL for webprint locally.

### DEV Notes ###
 
  
 null

### Design ###
 
  
 null

**Comment by sasha-dresden** [comment]
Successful print

![Image](https://github.com/fecgov/fecfile-web-api/assets/149604256/458398d0-ebae-42c8-9dfb-b2804284a1c3)

Changed FEC_FILING_API to "FAKE" to have a failed response and got this:

![Image](https://github.com/fecgov/fecfile-web-api/assets/149604256/779f652c-3f8b-4b70-b692-395fa37c861c)

**Comment by mjtravers** [comment]
Passes CR. For QA: See screenshots above showing error message saved to database when webprint has an issue connecting to the FEC api.

**Comment by WiseQA** [comment]
QA review completed per DEV screenshots showing error message saved to database when webprint has an issue connecting to the FEC api.

QA Review Completed.   Moved to Stage Ready.
