### ISSUE TITLE
Redirect failed logins to web app login page 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#888]
Business Reason

As a new FECFile user, I will be able to get back to FECFile login page from the login.gov page so that I can start over if I need to.

Acceptance Criteria

_**If**_ I'm on the login.gov sign in page _**When**_ I click "Back to FECFile" _**Then**_ I'm taken back to the FECFile login page ([https://fecfile-web-app-stage.app.cloud.gov/login](https://fecfile-web-app-stage.app.cloud.gov/login))

1.  ## Dev notes Investigate solution of creating an endpoint for the redirect URL

[dev-notes-investigate-solution-of-creating-an-endpoint-for-the-redirect-url](#dev-notes-investigate-solution-of-creating-an-endpoint-for-the-redirect-url)

[dev-notes-investigate-solution-of-creating-an-endpoint-for-the-redirect-url](#dev-notes-investigate-solution-of-creating-an-endpoint-for-the-redirect-url)

*   Open browser inspect / developer tools
*   Go to [https://fecfile-web-app-stage.app.cloud.gov/login](https://fecfile-web-app-stage.app.cloud.gov/login)
*   Click "Log in to FECFile"
*   Scroll to the bottom
*   Click "Back to FECFile (STAGE)"
*   Login.gov sends the user to [https://fecfile-web-api-dev.app.cloud.gov/oidc/callback/?error=access_denied&state=](https://fecfile-web-api-dev.app.cloud.gov/oidc/callback/?error=access_denied&state=)
*   This currently redirects to [https://fecfile-web-api-dev.app.cloud.gov/](https://fecfile-web-api-dev.app.cloud.gov/) which 404's
*   We should instead redirect to the web app signin page

> the link to go back to FECFile Web API (Stage) does not link correctly.
 > 
 > [![](https://github.com/fecgov/fecfile-web-api/assets/31420082/65c539c3-180e-4120-b077-46a853ea9607)](https://github.com/fecgov/fecfile-web-api/assets/31420082/65c539c3-180e-4120-b077-46a853ea9607)

For the broken "Back to FECFile" URL, I think we'll need to handle that on our end - on the API side, I believe. Login.gov sends the user to [https://fecfile-web-api-dev.app.cloud.gov/oidc/callback/?error=access_denied&state=](https://fecfile-web-api-dev.app.cloud.gov/oidc/callback/?error=access_denied&state=), which redirects to [https://fecfile-web-api-dev.app.cloud.gov/](https://fecfile-web-api-dev.app.cloud.gov/) which 404's. We should probably have a new ticket for this work. More info: [https://developers.login.gov/user-experience/cancel-url/](https://developers.login.gov/user-experience/cancel-url/)

_Originally posted by @lbeaufort in [https://github.com/fecgov/fecfile-web-app/issues/1868#issuecomment-2110311473_](https://github.com/fecgov/fecfile-web-app/issues/1868#issuecomment-2110311473_)

[https://github.com/fecgov/fecfile-web-api/blob/develop/manifests/manifest-dev-api.yml#L21C7-L21C27](https://github.com/fecgov/fecfile-web-api/blob/develop/manifests/manifest-dev-api.yml#L21C7-L21C27)

### QA Notes ###

To test, use steps in DEV notes. Log in and while on the Login.gov page, click "Back to FECFile"
See image below:

!image-20240605-195204.png|width=365,height=546,alt="image-20240605-195204.png"! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-159)   

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/d002e66b-8ddf-45d8-a509-adbf3651d6d5)

### DEV Notes ###

 
 null

### Design ###

 
 null

[FECFILE-159](https://fecgov.atlassian.net/browse/FECFILE-159)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers when selecting the "Back to FECFile (DEV)" from the login page:

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/3b29f529-6118-4128-8720-1afee9c7a4a6)

________________________________________________________________________

The following "Not Found" error message is received.

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/b0a43176-8224-41a0-9196-9e13f4a18e0c)

_______________________________________________________________________

@mjtravers waiting for review with DEV on this issue.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers per review of this ticket the redirect is failing.   Returned to In-Progress.

**Comment by mjtravers** [comment]
Passes CR and the "Back to FECFile" link is working for me. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified redirection when selecting the "Back to FECFile (DEV)" from the login page has been fixed and working as designed. 

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/ccc62832-d685-4c00-a819-d574592561a6)

____________________________________________________________________________

Return to Dashboard login landing page.

![Image](https://github.com/fecgov/fecfile-web-api/assets/96139912/ac037455-5566-4a29-957e-25f013b7014c)

___________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
