### ISSUE TITLE
Create cloud.gov environment variable for FEC API key

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#9]
Log into the Cloud.gov dashboard and create an environment variable for the FEC API key.

The name of the variable is documented in this ticket: [#31](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-online/31)

**ACCEPTANCE CRITERIA:**
- [x] FECFILE_FEC_WEBSITE_API_KEY visible in Cloud.gov dashboard for spaces develop, stage, and prod

**Comment by lbeaufort** [comment]
I confirmed that there need to be apps in cloud.gov in order to add environment variables.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/2/22:** Narrowed the scope of the ticket to just adding the API key variable, FECFILE_FEC_WEBSITE_API_KEY. Pointed at 1.

**Comment by WiseQA** [comment]
I don't see Code Review - reassigning to Matt.

**Comment by mjtravers** [comment]
No code to CR. Sending to QA

**Comment by toddlees** [comment]
screenshots of variables in dev, prod, and staging respectively
![cloud.gov-dev.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/aebe6628-5d6b-40a8-bd78-1db51d7c5923)
![cloud.gov-prod.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/a9110501-aa5d-4a95-b834-a2ac7cec87dc)
![cloud.gov-stage.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/86a23dc1-a268-4a7c-90e2-008234d624d7)

**Comment by WiseQA** [comment]
QA verified from screenshots (above) FECFILE_FEC_WEBSITE_API_KEY visible in Cloud.gov dashboard. 

QA review completed.  Moved to Stage Ready.
