### ISSUE TITLE
Build working example app for login.gov authentication workflow

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#90]
Build working example app for login.gov authentication workflow: 

**Demo app url**
https://login-demo.app.cloud.gov/simpleapp

**Demo app repo**
https://github.com/fecgov/login-gov-demo#readme
Evolution of app repo: https://github.com/fecgov/login-gov-demo/compare/0cb3f2fa6671d9f8665c93fa4433d69b1110a5cb...0db2636bb62f18ad1d3ceeca132f5433d1158abc

**OIDC code changes**
https://github.com/fecgov/mozilla-django-oidc/pull/1/files

**Setup notes**
https://docs.google.com/document/d/1LJVdS7CIVgd-9OmBnfSIaPCfH30iDTfF-4BGXFSSjFA/edit
**Login.gov folder**
https://drive.google.com/drive/folders/1nWOtt1pvUJQzHk0ZW_OQVwkTaP5DoauL

**Workflow diagram**
https://docs.google.com/drawings/d/1l5qDa7N_iU4MbSPZUKX2xrvknjEVFa70WhKMYcJFleU/edit

**Big picture**
- [x] Evaluate current strategy. Currently using forked copy of mozilla-django-oidc and modifying the client authentication step. do we want to move to just logindotgov-oidc? https://github.com/fecgov/logindotgov-oidc-py. For now, we're going to stick with what's working and re-evaluate once we get more parts working.

**Existing user (created with django superuser)**
- [x] Log in to site, using login.gov to authenticate, client authentication via token endpoint

**New user**
- [x] Log in to site, using login.gov to authenticate, client authentication via token endpoint, then new user is created (probably borrow from Mozilla for new user creation)
-  [X] User is created with both email and UUID - need to extend the Django model: https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#extending-the-existing-user-model
- [x] User is updated with latest email from login.gov 
- [x] Logging out should log out of login.gov session too https://developers.login.gov/oidc/#logout
- [x] Run Mozilla tests to see how they look, maybe get them working
- [x] Double-check TODO's for tech debt
- [ ] ~Add test coverage for `private_key_jwt` client auth method~ including in https://github.com/fecgov/fecfile-web-api/issues/112
- [ ] ~Linting on OIDC package~ included in tests, any major reformatting can be done in code cleanup ticket.

**Stretch goal**
- New ticket: https://github.com/fecgov/fecfile-web-api/issues/109 Smallest steps for login in web app. New, unauthenticated page with login/logout that goes to login.gov and then goes to the dashboard. Mozilla package adds OIDC endpoints, need to django rest framework integration.
- New ticket: https://github.com/fecgov/fecfile-web-api/issues/110 Make a plan for private key backup - s3 service in cloud.gov maybe? https://cloud.gov/docs/services/s3/  https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-storingprivatekeys.html
- Included in other new ticket: https://github.com/fecgov/fecfile-web-api/issues/109  web api code cleanup: remove old auth code, double check Django admin is disabled, 
-  New ticket: https://github.com/fecgov/fecfile-web-api/issues/112 OIDC package. Testing strategy for forked repo - should we be running/modifying these? 
- New ticket: https://github.com/fecgov/fecfile-web-api/issues/113  ODIC package, Remove sensitive data from debug statements, Look at exceptions in the logs, clean up comments,  Linting
- [x] Still getting random 403 forbidden from login.gov after logout is implemented
- [ ] ~Angular web app that talks to Django API? Session based? Web token? NOTE: Here is an article (there are a number to choose from) on using [JWT tokens with Django and Angular](https://www.metaltoad.com/blog/angular-api-calls-django-authentication-jwt), although I suspect the stretch goal here will be required to fix the [404 bug](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/190) use ng client?~ we'll do this on the main site
- [ ] ~Implement Django-rest-framework?~ will do this on the main site

### Business Reason ### 

As a user, I would like to log into the demo app by being redirected to Login.gov for authentication and then, upon successful authentication, sent back to the demo app. If I'm a new user, an account will be created for me

### Acceptance Criteria ### 

**If** logging into the app
**When** successfully sent to Login.gov and authenticating
**Then** I am redirected to the demo app

### QA ###
[Here is the login for the demo app to verify the work done](https://login-demo.app.cloud.gov/simpleapp/)

**Comment by lbeaufort** [comment]
There was some weirdness with the browser and copy/pasting env vars into the cloud.gov dashboard, so I set up a creds service so I can update the private key env var from the command line, but this was still problematic because you can't put multi-line strings in json. 

Here's what ultimately worked: 

`cf push -f manifest-dev.yml --vars-file .vars.yml`

**vars.yml:**
```
---
cert: |
  -----BEGIN PRIVATE KEY-----
  ...
  -----END PRIVATE KEY-----
```

**manifest-dev.yml:**
```
---
applications:
- name: login-demo
  route: login-demo-dev.app.cloud.gov
  buildpacks:
    - python_buildpack
  memory: 512M
  services:
    - login-demo-rds
    - login-creds
  env:
    DISABLE_COLLECTSTATIC: 1
    OIDC_RP_CLIENT_SECRET: ((cert))
```

manifests are additive-only, so I removed the OIDC_RP_CLIENT_SECRET cert from the manifest and it will persist unless the app gets deleted.
We would need a safe place to store the certificates if we needed to delete the app for some reason.

**Comment by lbeaufort** [comment]
Demo notes:

- Show app setup in login.gov sandbox: https://dashboard.int.identitysandbox.gov/service_providers
- Log in with new email (create new gmail)
- Log out
- Show users in admin interface

**Comment by WiseQA** [comment]
QA review and visual completed with above links in acceptance criteria.
QA completed moved to Stage Ready.
