### ISSUE TITLE
Remove FILE_AS_TEST_COMMITTEE and TEST_COMMITTEE_PASSWORD settings

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#902]
Remove `FILE_AS_TEST_COMMITTEE` and `TEST_COMMITTEE_PASSWORD` settings

Business Reason

As a developer, I will be able to understand application configuration so that I can fix issues as they arrive.

### QA Notes ###

null

### DEV Notes ###

 
The api settings FILE_AS_TEST_COMMITTEE and TEST_COMMITTEE_PASSWORD were used prior to our setup of creating unique committees for each test user. These settings are OBE and can be removed from the code base.

Locations to remove:
- [x] base settings file
- [x] web_services app
- [x] Docker compose file
- [x] Cloud.gov credentials services in DEV
- [ ] Cloud.gov credentials services in STAGE
- [ ] Cloud.gov credentials services in PROD

## QA Notes ##
To test, the ticket is successful if a user can submit a filing to Test EFO without error. Just 1 test submission is sufficient.

### Design ###

null

[FECFILE-1410](https://fecgov.atlassian.net/browse/FECFILE-1410)

**Comment by dheitzer** [comment]
Tested/confirmed on local:


![Image](https://github.com/fecgov/fecfile-web-api/assets/104843885/35b63566-b524-4f2c-840b-e6728f3af5af)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Here are the unit tests passing:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3838/workflows/1cb05452-d818-430c-8120-d190ad6702f8/jobs/11567

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/a5da3da2-4812-4885-b9d1-c702c82d8a35)


Also, the updates to the credential will be performed in each cloud.gov space after the code has been deployed to each space. DEV credential have been updated. The checkbox for the ticket item will be checked off after STAGE and PROD have been updated after deployment.

**Comment by WiseQA** [comment]
QA review completed verifying DEV unit tests passing for this ticket.

QA Review Completed.  Moved to Stage Ready.
