### ISSUE TITLE
Performance Improvements - Report Recalculation Flagging

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-web-api#917]
When flagging reports for recalculation, individual reports are instantiated just to update a single field, and this has an outsized impact on the response time for creating transactions. Instead of instantiating each report, we should instead call `.update()` on the filtered queryset to change just the field in question.

### QA Notes ###

After creating or updating a transaction, when you go to a different report with coverage dates later in the same year, the summary page should need to recalculate.

### DEV Notes ###

null

### Design ###

null

[FECFILE-1429](https://fecgov.atlassian.net/browse/FECFILE-1429)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @Elaine-Krauss-TCG can there please be unit tests showing this ticket passing and screenshots as we always do.  Thanks
