### ISSUE TITLE
[High] Update `gunicorn` to 22.0.0

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#933]
Business Reason

[https://app.snyk.io/org/fecfile/project/e7c50dce-96a9-4313-818b-069a631aa5bc#issue-SNYK-PYTHON-GUNICORN-6615672](https://app.snyk.io/org/fecfile/project/e7c50dce-96a9-4313-818b-069a631aa5bc#issue-SNYK-PYTHON-GUNICORN-6615672)

As a [role], I will be able to [blank] so that I can [business reason]

Acceptance Criteria

**If** [precedent] **When** [action] **Then** [result]

### QA Notes ###

null

### DEV Notes ###

null

### Design ###

null

[FECFILE-1440](https://fecgov.atlassian.net/browse/FECFILE-1440)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

Unit tests passed:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/3862/workflows/95047275-43fa-45dc-bdd1-bed46fafe47f/jobs/11636


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/44013b69-dc9e-438c-9d05-834a3797eeb4)
