### ISSUE TITLE
Update silk performance testing instructions

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-web-api#938]
Business Reason

As a developer, I will be able to find instructions for setting up and using Silk Profiling in the performance testing README.

Acceptance Criteria

The README in the locust-testing directory (renamed: performance-testing) should contain instructions to help devs quickly set up Silk testing and access the results.

### QA Notes ###

No code changes are being made in this ticket.

### DEV Notes ###

null

### Design ###

null

[FECFILE-1445](https://fecgov.atlassian.net/browse/FECFILE-1445)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

For QA: Documentation was added to the repo regarding the Silk query profiler

Can be verified on this page: https://github.com/fecgov/fecfile-web-api/blob/develop/performance-testing/README.md#silk-profiling

![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/d021440f-0fbd-4491-85bf-7dbd8111e110)

**Comment by WiseQA** [comment]
QA review verified documentation was added to the repo regarding the Silk query profiler per link above provided by DEV.

QA Review Completed. Moved to Stage Ready.
